/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version fusioncharts/3.3.1-release.19520
*/
FusionCharts(["private","modules.renderer.js-charts",function(){function Aa(a){for(var K={left:a.offsetLeft,top:a.offsetTop},a=a.offsetParent;a;)K.left+=a.offsetLeft,K.top+=a.offsetTop,a!==Ba.body&&a!==Ba.documentElement&&(K.left-=a.scrollLeft,K.top-=a.scrollTop),a=a.offsetParent;return K}function ha(a,K){for(var c=[],f=0,x=a.length;f<x;f++)c[f]=K.call(a[f],a[f],f,a);return c}function wa(a){a=(a||0)%ga;return a<0?ga+a:a}function ya(a,K){return a<=O?a:K<=O?K:K>a?0:K}function Ja(a,K,c,f,x){return Q((K-
c[1]-f.top)/x,a-c[0]-f.left)}function na(a,K,c,f,x,b,j,w,e,o){if(typeof a==="object")K=a.y,c=a.r,f=a.innerR,x=a.radiusYFactor,b=a.depth,j=a.seriesGroup,w=a.renderer,a=a.x;if(x<0||x>=1)x=0.6;a=a||0;K=K||0;c=c||1;f=f||0;b=b||0;this.renderer=w;this.hasOnePoint=e;this.use3DLighting=o;this.cx=a;this.cy=K;this.rx=c;this.ry=c*x;this.radiusYFactor=x;this.isDoughnut=f>0;this.innerRx=f;this.innerRy=f*x;this.depth=b;this.leftX=a-c;this.rightX=a+c;this.leftInnerX=a-f;this.rightInnerX=a+f;this.depthY=K+b;this.topY=
K-this.ry;this.bottomY=this.depthY+this.ry;this.bottomBorderGroup=w.group("bottom-border",j).attr({transform:"t0,"+b});this.outerBackGroup=w.group("outer-back-Side",j);this.slicingWallsBackGroup=w.group("slicingWalls-back-Side",j);this.innerBackGroup=w.group("inner-back-Side",j);this.innerFrontGroup=w.group("inner-front-Side",j);this.slicingWallsFrontGroup=w.group("slicingWalls-front-Side",j);this.topGroup=w.group("top-Side",j);this.moveCmdArr=[d];this.lineCmdArr=[t];this.closeCmdArr=[A];this.centerPoint=
[a,K];this.leftPoint=[this.leftX,K];this.topPoint=[a,this.topY];this.rightPoint=[this.rightX,K];this.bottomPoint=[a,K+this.ry];this.leftDepthPoint=[this.leftX,this.depthY];this.rightDepthPoint=[this.rightX,this.depthY];this.leftInnerPoint=[this.leftInnerX,K];this.rightInnerPoint=[this.rightInnerX,K];this.leftInnerDepthPoint=[this.leftInnerX,this.depthY];this.rightInnerDepthPoint=[this.rightInnerX,this.depthY];this.pointElemStore=[];this.slicingWallsArr=[];a=[h,this.rx,this.ry,0,0,1,this.rightX,K];
c=[h,this.rx,this.ry,0,0,1,this.leftX,K];f=[h,this.rx,this.ry,0,0,0,this.rightX,this.depthY];x=[h,this.rx,this.ry,0,0,0,this.leftX,this.depthY];b=[h,this.innerRx,this.innerRy,0,0,0,this.rightInnerX,K];K=[h,this.innerRx,this.innerRy,0,0,0,this.leftInnerX,K];j=[h,this.innerRx,this.innerRy,0,0,1,this.rightInnerX,this.depthY];w=[h,this.innerRx,this.innerRy,0,0,1,this.leftInnerX,this.depthY];this.isDoughnut?(this.topBorderPath=this.moveCmdArr.concat(this.leftPoint,a,c,this.moveCmdArr,this.leftInnerPoint,
b,K),this.topPath=this.moveCmdArr.concat(this.leftPoint,a,c,this.lineCmdArr,this.leftInnerPoint,b,K,this.closeCmdArr),this.innerFrontPath=this.moveCmdArr.concat(this.leftInnerPoint,b,this.lineCmdArr,this.rightInnerDepthPoint,w,this.closeCmdArr),this.innerBackPath=this.moveCmdArr.concat(this.rightInnerPoint,K,this.lineCmdArr,this.leftInnerDepthPoint,j,this.closeCmdArr)):this.topBorderPath=this.topPath=this.moveCmdArr.concat(this.leftPoint,a,c,this.closeCmdArr);this.outerBackPath=this.moveCmdArr.concat(this.leftPoint,
a,this.lineCmdArr,this.rightDepthPoint,x,this.closeCmdArr);this.outerFrontPath=this.moveCmdArr.concat(this.rightPoint,c,this.lineCmdArr,this.leftDepthPoint,f,this.closeCmdArr);this.clipPathforOuter=[d,this.leftX,this.topY,t,this.rightX,this.topY,this.rightX,this.bottomY,this.leftX,this.bottomY,A];this.clipPathforInner=[d,this.leftInnerX,this.topY,t,this.rightInnerX,this.topY,this.rightInnerX,this.bottomY,this.leftInnerX,this.bottomY,A];this.clipPathforNoClip=[d,this.leftInnerX,this.topY,t,this.leftInnerX,
this.bottomY,A]}var Ca=this,u=Ca.hcLib,D=u.Raphael,Ba=window.document,F=u.BLANKSTRING,Oa=u.createTrendLine,q=u.pluck,ta=u.getValidValue,g=u.pluckNumber,Z=u.defaultPaletteOptions,Da=u.getFirstValue,ua=u.getDefinedColor,pa=u.parseUnsafeString,ea=u.FC_CONFIG_STRING,Ea=u.extend2,Ka=u.getDashStyle,L=u.toRaphaelColor,Fa=u.toPrecision,La=u.stubFN,Y=u.hasSVG,za=u.isIE,ia=u.each,b=u.hasTouch?10:3,e="rgba(192,192,192,"+(za?0.0020:1.0E-6)+")",l=document.documentMode===8?"visible":"",d="M",t="L",h="A",A="Z",
n=Math,ba=n.sin,T=n.cos,Q=n.atan2,s=n.round,X=n.min,M=n.max,Ga=n.abs,W=n.PI,oa=n.floor,R=n.sqrt,qa=W/180,O=Math.PI,fa=O/2,ga=2*O,V=O+fa,da=u.graphics.getColumnColor,U=u.getFirstColor,ja=u.setLineHeight,Ha=u.pluckFontSize,Ma=u.getFirstAlpha,ca=u.graphics.getDarkColor,ka=u.graphics.getLightColor,ra=u.graphics.convertColor,Na=u.COLOR_TRANSPARENT,e="rgba(192,192,192,"+(za?0.0020:1.0E-6)+")",Qa=u.POSITION_CENTER,Sa=u.POSITION_TOP,Ra=u.POSITION_BOTTOM,Ta=u.POSITION_RIGHT,Ua=u.POSITION_LEFT,k=u.chartAPI,
Va=u.titleSpaceManager,Wa=u.placeLegendBlockBottom,Xa=u.placeLegendBlockRight,Ya=u.graphics.mapSymbolName,za=k.singleseries,J=u.COMMASTRING,va=u.ZEROSTRING,Ia=u.ONESTRING,xa=u.HUNDREDSTRING,Pa=u.PXSTRING,Za=u.COMMASPACE,sa=!/fusioncharts\.com$/i.test(location.hostname);k("column2d",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},k.column2dbase);k("column3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},k.column2d);k("bar2d",{isBar:!0,defaultSeriesType:"bar",
spaceManager:k.barbase},k.column2d);k("line",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},k.linebase);k("area2d",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},k.area2dbase);k("pie2d",{standaloneInit:!0,defaultSeriesType:"pie",defaultPlotShadow:1,sliceOnLegendClick:!0,rendererId:"pie",point:function(a,K,c,f,x){var b,j,w,e=x[ea],o=e.is3d,m,v,i,d,h=0,B=0,l=[];w=g(f.plotborderthickness);var t=g(w,o?0.1:1),p=(m=g(f.use3dlighting,1))?g(f.radius3d,f["3dradius"],90):100;v=g(f.showzeropies,
1);var y=g(f.showpercentintooltip,1),k=g(f.showlabels,1),I=g(f.showvalues,1),n=g(f.showpercentvalues,f.showpercentagevalues,0),G=q(f.tooltipsepchar,f.hovercapsepchar,Za),r=q(f.labelsepchar,G),z=q(f.plotbordercolor,f.piebordercolor),E=x[ea].numberFormatter;i=c.length;var A,s,C=g(f.plotborderdashed,0),H=g(f.plotborderdashlen,5),N=g(f.plotborderdashgap,4);p>100&&(p=100);p<0&&(p=0);if(g(f.showlegend,0))x.legend.enabled=!0,x.legend.reversed=!Boolean(g(f.reverselegend,0)),K.showInLegend=!0;for(a=0;a<i;a+=
1)j=c[a],b=E.getCleanValue(j.value,!0),b===null||!v&&b===0||(l.push(j),h+=b);h===0&&(l=[]);K.enableRotation=l.length>1?g(f.enablerotation,1):0;K.alphaAnimation=g(f.alphaanimation,1);K.is3D=o;K.use3DLighting=m;K.pieYScale=g(f.pieyscale,40);if(K.pieYScale<1)K.pieYScale=1;if(K.pieYScale>=100)K.pieYScale=80;K.pieYScale/=100;K.pieSliceDepth=g(f.pieslicedepth,15);if(K.pieSliceDepth<1)K.pieSliceDepth=1;K.managedPieSliceDepth=K.pieSliceDepth;if(o&&f.showplotborder!=Ia&&!w)K.showBorderEffect=1;for(a=l.length-
1;a>=0;a-=1){j=l[a];b=E.getCleanValue(j.value,!0);c=pa(q(j.label,j.name,F));m=q(j.color,x.colors[a%x.colors.length]);v=q(j.alpha,f.plotfillalpha);i=q(j.bordercolor,z);d=q(j.borderalpha,f.plotborderalpha,f.pieborderalpha);if(o&&(i||d!==void 0))K.showBorderEffect=0;i=q(i,ka(m,o?90:25)).split(J)[0];d=f.showplotborder==va?va:q(d,v,"80");v=q(v,xa);w={opacity:Math.max(v,d)/100};if(A=Boolean(g(j.issliced,f.issliced,0)))e.preSliced=A;s=g(j.dashed,C)?Ka(q(j.dashlen,H),q(j.dashgap,N),t):void 0;K.data.push({showInLegend:c!==
F,y:b,name:c,shadow:w,toolText:pa(ta(j.tooltext)),color:this.getPointColor(m,v,p),_3dAlpha:v,borderColor:ra(i,d),borderWidth:t,link:ta(j.link),sliced:A,dashStyle:s,doNotSlice:q(f.enableslicing,Ia)!=Ia});v=E.percentValue(b/h*100);i=E.dataLabels(b)||F;w=y===1?v:i;b=g(j.showlabel,k)===1?c:F;v=(m=g(j.showvalue,I))===1?n===1?v:i:F;j=ta(pa(j.displayvalue));v=j!==void 0&&m?j:v!==F&&b!==F?b+r+v:q(b,v);c=c!=F?c+G+w:w;j=K.data[B];j.displayValue=v;j.toolText=q(j.toolText,c);B+=1}K.valueTotal=h;x.legend.enabled=
f.showlegend==Ia?!0:!1;K.startAngle=g(f.startingangle,0);x.chart.startingAngle=q(l.length>1?f.startingangle:0,0);return K},getPointColor:function(a,K,c){var f,b,a=U(a),K=Ma(K);c<100&&Y?(f=Math.floor((100-0.35*c)*85)/100,f=ca(a,f),b=Math.floor((100+c)*50)/100,a=ka(a,b),K={FCcolor:{color:a+J+f,alpha:K+J+K,ratio:c+",100",radialGradient:!0,gradientUnits:"userSpaceOnUse"}}):K={FCcolor:{color:a+J+a,alpha:K+J+K,ratio:"0,100"}};return K},configureAxis:function(a){var K=0,c=a[ea],f;a.plotOptions.series.dataLabels.style=
a.xAxis.labels.style;a.plotOptions.series.dataLabels.color=a.xAxis.labels.style.color;delete c.x;delete c[0];delete c[1];a.chart.plotBorderColor=a.chart.plotBackgroundColor=Na;c=c.pieDATALabels=[];if(a.series.length===1&&(f=a.series[0].data)&&(K=a.series[0].data.length)>0&&a.plotOptions.series.dataLabels.enabled)for(;K--;)f[K]&&ta(f[K].displayValue)!==void 0&&c.push(f[K].displayValue)},spaceManager:function(a,K,c,f){var b=a[ea],e=b.is3d,j=this.name,w=b.smartLabel,d=g(b.pieDATALabels&&b.pieDATALabels.length,
0),o=0,m=K.chart,v=g(m.managelabeloverflow,0),i=!b.preSliced&&m.enableslicing==va&&(m.showlegend!=Ia||m.interactivelegend==va)?0:g(m.slicingdistance,20),h=g(m.pieradius,0),l=g(m.enablesmartlabels,m.enablesmartlabel,1),B=l?g(m.skipoverlaplabels,m.skipoverlaplabel,1):0,t=g(m.issmartlineslanted,1),k=g(m.labeldistance,m.nametbdistance,5),p=g(m.smartlabelclearance,5);c-=a.chart.marginRight+a.chart.marginLeft;var y=f-(a.chart.marginTop+a.chart.marginBottom),f=Math.min(y,c),$a=q(m.smartlinecolor,Z.plotFillColor[a.chart.paletteIndex]),
I=g(m.smartlinealpha,100),n=g(m.smartlinethickness,1),G=a.plotOptions.series.dataLabels,r=G.style,z=g(parseInt(r.lineHeight,10),12),E=a.series[0]||{},A=E.pieYScale,s=E.pieSliceDepth,f=h===0?f*0.15:h,C=0,C=2*f;G.connectorWidth=n;G.connectorPadding=g(m.connectorpadding,5);G.connectorColor=ra($a,I);y-=Va(a,K,c,C<y?y-C:y/2);m.showlegend==Ia&&(q(m.legendposition,Ra).toLowerCase()!=Ta?y-=Wa(a,K,c,y/2,!0):c-=Xa(a,K,c/3,y,!0));w.setStyle(r);if(d!==1)for(;d--;)K=w.getOriSize(b.pieDATALabels[d]),o=Math.max(o,
K.width);l&&(k=p+i);h===0&&(e?(y-=s,C=Math.min(c/2-o,(y/2-z)/A)-k):C=Math.min(c/2-o,y/2-z)-k,C>=f?f=C:k=Math.max(k-(f-C),i));if(e&&(d=y-2*(f*A+z),s>d))E.managedPieSliceDepth=s-d;a.plotOptions.pie3d.slicedOffset=a.plotOptions.pie.slicedOffset=i;a.plotOptions.pie3d.size=a.plotOptions.pie.size=2*f;a.plotOptions.series.dataLabels.distance=k;a.plotOptions.series.dataLabels.isSmartLineSlanted=t;a.plotOptions.series.dataLabels.enableSmartLabels=l;a.plotOptions.series.dataLabels.skipOverlapLabels=B;a.plotOptions.series.dataLabels.manageLabelOverflow=
v;if(j==="doughnut2d"||j==="doughnut3d")if(j=g(m.doughnutradius,0),d=g(m.use3dlighting,1)?g(m.radius3d,m["3dradius"],50):100,d>100&&(d=100),d<0&&(d=0),m=j===0||j>=f?f/2:j,a.plotOptions.pie3d.innerSize=a.plotOptions.pie.innerSize=2*m,d>0&&Y&&(m=parseInt(m/f*100,10),j=(100-m)/2,d=parseInt(j*d/100,10),m=m+J+d+J+2*(j-d)+J+d,a.series[0]&&a.series[0].data)){v=a.series[0].data;a=0;for(d=v.length;a<d;a+=1)if(j=v[a],j.color.FCcolor)j.color.FCcolor.ratio=m}},creditLabel:sa,eiMethods:{sliceDataItem:function(a){var b=
this.jsVars.hcObj,c;if(b&&b.datasets&&(c=b.datasets[0])&&c.data&&c.data[a]&&c.data[a].plot)return b.plotGraphicClick.call(c.data[a].plot)}}},za);k.pie2d.eiMethods.togglePieSlice=k.pie2d.eiMethods.sliceDataItem;k.pie2d.eiMethods.enableSlicingMovement=k.pie2d.eiMethods.enablelink=function(){Ca.raiseWarning(this,"1301081430","run","JSRenderer~enablelink()","Method deprecated.")};k("pie3d",{defaultSeriesType:"pie3d",rendererId:"pie3d",creditLabel:sa,getPointColor:function(a){return a},defaultPlotShadow:0},
k.pie2d);k("doughnut2d",{getPointColor:function(a,b,c){var f,x,a=U(a),b=Ma(b);c<100&&Y?(f=Math.floor((85-0.2*(100-c))*100)/100,f=ca(a,f),x=Math.floor((100-0.5*c)*100)/100,a=ka(a,x),b={FCcolor:{color:f+J+a+J+a+J+f,alpha:b+J+b+J+b+J+b,radialGradient:!0,gradientUnits:"userSpaceOnUse",r:c}}):b={FCcolor:{color:a+J+a,alpha:b+J+b,ratio:"0,100"}};return b}},k.pie2d);k("doughnut3d",{defaultSeriesType:"pie3d",rendererId:"pie3d",getPointColor:k.pie3d,defaultPlotShadow:0},k.doughnut2d);k("pareto2d",{standaloneInit:!0,
point:function(a,b,c,f,x){var d,j,w,e,o,m,v,i,h,l,B,t,k,p,y,a=c.length,n=0;m={};k=x.chart.paletteIndex;var I=/3d$/.test(x.chart.defaultSeriesType),A=this.isBar,G=q(360-f.plotfillangle,90),r=g(f.plotborderthickness,1),z=x.chart.useRoundEdges,E=q(f.tooltipsepchar,", "),s=q(f.plotbordercolor,Z.plotBorderColor[k]).split(J)[0],ba=f.showplotborder==va?va:q(f.plotborderalpha,f.plotfillalpha,xa),C=x.xAxis,H=g(f.showcumulativeline,1),N=x[ea],P=N.axisGridManager,T=N.x,u=f.showtooltip!=va,S=[],O=[],Q=g(f.use3dlighting,
1),M=x[ea].numberFormatter,X=g(f.showlinevalues,f.showvalues),D=g(f.plotborderdashed,0),R=g(f.plotborderdashlen,5),V=g(f.plotborderdashgap,4),ba=I?f.showplotborder?ba:va:ba,s=I?q(f.plotbordercolor,"#FFFFFF"):s;for(t=j=0;j<a;j+=1)if(B=c[j],c[j].vline)P.addVline(C,B,t,x);else if(d=M.getCleanValue(B.value,!0),d!==null)B.value=d,S.push(B),t+=1;a=S.length;S.sort(function(a,c){return c.value-a.value});if(H)v=g(f.linedashed,0),p=U(q(f.linecolor,Z.plotBorderColor[k])),j=q(f.linealpha,100),i=g(f.linedashlen,
5),h=g(f.linedashgap,4),m=g(f.linethickness,2),l={opacity:j/100},y=g(f.drawanchors,f.showanchors),y===void 0&&(y=j!=va),w=g(f.anchorborderthickness,1),o=g(f.anchorsides,0),e=g(f.anchorradius,3),t=U(q(f.anchorbordercolor,p)),d=U(q(f.anchorbgcolor,Z.anchorBgColor[k])),c=Ma(q(f.anchoralpha,xa)),B=Ma(q(f.anchorbgalpha,c))*c/100,v=v?Ka(i,h,m):void 0,m={yAxis:1,data:[],type:"line",color:{FCcolor:{color:p,alpha:j}},lineWidth:m,marker:{enabled:y,fillColor:{FCcolor:{color:d,alpha:B}},lineColor:{FCcolor:{color:t,
alpha:c}},lineWidth:w,radius:e,symbol:Ya(o),startAngle:q(f.anchorstartangle,90)}};else{if(f.showsecondarylimits!=="1")f.showsecondarylimits="0";if(f.showdivlinesecondaryvalue!=="1")f.showdivlinesecondaryvalue="0"}for(j=0;j<a;j+=1)B=S[j],d=g(B.showlabel,f.showlabels,1),c=pa(!d?F:Da(B.label,B.name)),P.addXaxisCat(C,j,j,c),n+=d=B.value,w=q(B.color,x.colors[j%x.colors.length])+J+(g(f.useplotgradientcolor,1)?ua(f.plotgradientcolor,Z.plotGradientColor[k]):F),e=q(B.alpha,f.plotfillalpha,xa),o=q(B.ratio,
f.plotfillratio),t={opacity:e/100},p=q(B.alpha,ba)+F,w=da(w,e,o,G,z,s,p,A,I),b.data.push(Ea(this.getPointStub(B,d,c,x),{y:d,shadow:t,color:w[0],borderColor:w[1],borderWidth:r,use3DLighting:Q,dashStyle:g(B.dashed,D)==1?Ka(R,V,r):"",tooltipConstraint:this.tooltipConstraint})),this.pointValueWatcher(x,d),H&&O.push({value:n,dataLabel:c,tooltext:ta(B.tooltext)});T.catCount=a;N[1]||(N[1]={});N[1].stacking100Percent=!0;if(H&&n>0){j=0;for(a=O.length;j<a;j+=1)B=O[j],x=b.data[j],d=B.value/n*100,k=M.percentValue(d),
f=x.displayValue!==F?k:F,X==1&&(f=k),X==0&&(f=F),c=B.dataLabel,k=u?B.tooltext!==void 0?B.tooltext:(c!==F?c+E:F)+k:F,m.data.push({shadow:l,color:m.color,marker:m.marker,y:d,toolText:k,displayValue:f,link:x.link,dashStyle:v});return[b,m]}else return b},defaultSeriesType:"column",isDual:!0,creditLabel:sa,rendererId:"cartesian"},za);k("pareto3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0},k.pareto2d);k("mscolumn2d",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},k.mscolumn2dbase);
k("mscolumn3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},k.mscolumn2d);k("msbar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:k.barbase},k.mscolumn2d);k("msbar3d",{defaultSeriesType:"bar3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},k.msbar2d);k("msline",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},k.mslinebase);k("msarea",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},k.msareabase);k("stackedcolumn2d",{isStacked:!0},
k.mscolumn2d);k("stackedcolumn3d",{isStacked:!0},k.mscolumn3d);k("stackedbar2d",{isStacked:!0},k.msbar2d);k("stackedbar3d",{isStacked:!0},k.msbar3d);k("stackedarea2d",{isStacked:!0,areaAlpha:100,showSum:0},k.msarea);k("marimekko",{isValueAbs:!0,distributedColumns:!0,isStacked:!0,xAxisMinMaxSetter:La,postSeriesAddition:function(a,b){var c=a[ea],f=0,x=a.xAxis,d=100/c.marimekkoTotal,j=[],w=a.series,e=0,o=g(b.chart.plotborderthickness,1),m=a.chart.rotateValues,v=g(b.chart.rotatexaxispercentvalues,0),
o=o*-0.5-(o%2+(v?0:4)),i=v?3:0,h=m?270:0,l=Ea({},a.plotOptions.series.dataLabels.style),B=parseInt(l.fontSize,10),k=c[0],t=k.stacking100Percent,p=!t,y=c.inCanvasStyle,n=this.numberFormatter,I=b.categories&&b.categories[0]&&b.categories[0].category||[],A=0,G=[],r,z,E,q,ba,C,H,N;c.isXYPlot=!0;c.distributedColumns=!0;x.min=0;x.max=100;x.labels.enabled=!1;x.gridLineWidth=0;x.alternateGridColor=Na;r=k.stack;b.chart.interactivelegend="0";k=0;for(z=a.xAxis.plotLines.length;k<z;k+=1)if(E=x.plotLines[k],E.isGrid)E.isCat=
!0,j[E.value]=E,E._hideLabel=!0;for(k=z=0;k<I.length;k+=1)I[k].vline||(A+=G[z]=n.getCleanValue(I[k].widthpercent||0),z+=1);x=r.floatedcolumn&&r.floatedcolumn[0]||[];if(A===100&&(x&&x.length)!==z)for(;z--;)x[z]||(x[z]={p:null});A=s(A);if(x){q=0;for(z=x.length;q<z;){N=x[q];f+=E=N&&N.p||0;C=A===100?G[q]:E*d;ba=e+C/2;H=e+C;for(k=0;k<w.length;k+=1)if(I=a.series[k].data[q],I._FCX=e,I._FCW=C,t){if(I.y||I.y===0){r=I.y/E*100;I.y=r;if(I.showPercentValues)I.displayValue=this.numberFormatter.percentValue(r);
if(I.showPercentInToolTip)I.toolText=I.toolText+parseInt(r*100,10)/100+"%"}if(I.previousY||I.previousY===0)I.previousY=I.previousY/E*100}c.showStackTotal&&a.xAxis.plotLines.push({value:ba,width:0,isVline:p,isTrend:!p,_isStackSum:1,zIndex:4,label:{align:Qa,textAlign:h,rotation:m?270:0,style:l,verticalAlign:Sa,offsetScale:p?E<0?N.n:N.p:void 0,offsetScaleIndex:0,y:E<0?m===270?4:B:-4,x:0,text:n.yAxis(Fa(E,10))}});if(j[q])j[q].value=ba,j[q]._weight=C,j[q]._hideLabel=!1;q+=1;c.showXAxisPercentValues&&q<
z&&a.xAxis.plotLines.push({value:H,width:0,isVine:!0,label:{align:Qa,textAlign:v?Ua:Qa,rotation:v?270:0,backgroundColor:"#ffffff",backgroundOpacity:1,borderWidth:"1px",borderType:"solid",borderColor:y.color,style:{color:y.color,fontSize:y.fontSize,fontFamily:y.fontFamily,lineHeight:y.lineHeight},verticalAlign:Ra,y:o,x:i,text:this.numberFormatter.percentValue(H)},zIndex:5});e=H}}q=0;for(z=j.length;q<z;q+=1)if(j[q]&&j[q]._hideLabel)j[q].value=null},defaultSeriesType:"floatedcolumn"},k.stackedcolumn2d);
k("msstackedcolumn2d",{series:function(a,b,c){var f,x,d,j,w=b[ea],e=0,o,m;o=[];var v;b.legend.enabled=Boolean(g(a.chart.showlegend,1));if(a.dataset&&a.dataset.length>0){this.categoryAdder(a,b);f=0;for(x=a.dataset.length;f<x;f+=1)if(v=a.dataset[f].dataset){d=0;for(j=v.length;d<j;d+=1,e+=1)o={visible:!!g(v.visible,1),data:[],numColumns:x,columnPosition:f},m=Math.min(w.oriCatTmp.length,v[d].data&&v[d].data.length),o=this.point(c,o,v[d],a.chart,b,m,e,f),b.series.push(o)}if(this.isDual&&a.lineset&&a.lineset.length>
0){d=0;for(j=a.lineset.length;d<j;d+=1,e+=1)o={visible:!!g(a.lineset[d].visible,1),data:[],yAxis:1,type:"line"},c=a.lineset[d],m=Math.min(w.oriCatTmp.length,c.data&&c.data.length),b.series.push(k.msline.point.call(this,"msline",o,c,a.chart,b,m,e))}this.configureAxis(b,a);a.trendlines&&Oa(a.trendlines,b.yAxis,b[ea],!1,this.isBar)}},postSpaceManager:function(a,b,c){var i;var f=a[ea],x,d,j;if(this.isStacked&&f.showStackTotal&&(x=a.chart,i=(b=a.xAxis)&&b.plotLines,a=i,x=c-x.marginLeft-x.marginRight,c=
f.plotSpacePercent,f=f[0].stack,f=f.column&&f.column.length,b=x/(b.max-b.min),b*((1-2*c)/f)>50&&c==0.1)){b=50/b;c=a&&a.length;f=-((f-1)/2)*b;for(j=0;j<c;j+=1)if(d=a[j],d._isStackSum)x=d._catPosition+(f+b*d._stackIndex),d.value=x}}},k.stackedcolumn2d);k("mscombi2d",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},k.mscombibase);k("mscombi3d",{series:k.mscombi2d.series,eiMethods:function(a){var b={};ia(a.split(","),function(a){b[a]=function(){Ca.raiseWarning(this,"1301081430","run","JSRenderer~"+
a+"()","Method not applicable.")}});return b}("view2D,view3D,resetView,rotateView,getViewAngles,fitToStage")},k.mscolumn3d);k("mscolumnline3d",{},k.mscombi3d);k("stackedcolumn2dline",{isStacked:!0,stack100percent:0},k.mscombi2d);k("stackedcolumn3dline",{isStacked:!0,stack100percent:0},k.mscombi3d);k("mscombidy2d",{isDual:!0,secondarySeriesType:void 0},k.mscombi2d);k("mscolumn3dlinedy",{isDual:!0,secondarySeriesType:"line"},k.mscolumnline3d);k("stackedcolumn3dlinedy",{isDual:!0,secondarySeriesType:"line"},
k.stackedcolumn3dline);k("msstackedcolumn2dlinedy",{isDual:!0,stack100percent:0,secondarySeriesType:"line"},k.msstackedcolumn2d);k("scrollcolumn2d",{postSeriesAddition:k.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},k.mscolumn2d);k("scrollline2d",{postSeriesAddition:k.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:75},k.msline);k("scrollarea2d",{postSeriesAddition:k.scrollbase.postSeriesAddition,
tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:75},k.msarea);k("scrollstackedcolumn2d",{postSeriesAddition:function(a,b,c,f){k.base.postSeriesAddition.call(this,a,b,c,f);k.scrollbase.postSeriesAddition.call(this,a,b,c,f)},canvasborderthickness:1,tooltipConstraint:"plot",avgScrollPointWidth:75},k.stackedcolumn2d);k("scrollcombi2d",{postSeriesAddition:k.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},k.mscombi2d);k("scrollcombidy2d",
{postSeriesAddition:k.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},k.mscombidy2d);k("scatter",{standaloneInit:!0,defaultSeriesType:"scatter",defaultZeroPlaneHighlighted:!1,creditLabel:sa},k.scatterbase);k("bubble",{standaloneInit:!0,standaloneInut:!0,defaultSeriesType:"bubble",rendererId:"bubble",point:function(a,b,c,f,x,d,j){if(c.data){var w,e,o,m,v,i,h,l,B,t,n=!1,p,y,a=k[a],d=c.data,A=d.length,I=g(c.showvalues,x[ea].showValues);o=g(f.bubblescale,
1);var s=q(f.negativecolor,"FF0000"),G=x.plotOptions.bubble,r=this.numberFormatter,z=g(c.showregressionline,f.showregressionline,0);G.bubbleScale=o;b.name=ta(c.seriesname);if(g(c.includeinlegend)===0||b.name===void 0)b.showInLegend=!1;o=Boolean(g(c.drawanchors,c.showanchors,f.drawanchors,1));h=q(c.plotfillalpha,c.bubblefillalpha,f.plotfillalpha,xa);l=g(c.showplotborder,f.showplotborder,1);B=U(q(c.plotbordercolor,f.plotbordercolor,"666666"));w=q(c.plotborderthickness,f.plotborderthickness,1);t=q(c.plotborderalpha,
f.plotborderalpha,"95");l=l==1?w:0;j=q(c.color,c.plotfillcolor,f.plotfillcolor,x.colors[j%x.colors.length]);b.marker={enabled:o,fillColor:this.getPointColor(j,xa),lineColor:{FCcolor:{color:B,alpha:t}},lineWidth:l,symbol:"circle"};if(z){b.events={hide:this.hideRLine,show:this.showRLine};var E={sumX:0,sumY:0,sumXY:0,sumXsqure:0,sumYsqure:0,xValues:[],yValues:[]},ba=g(c.showyonx,f.showyonx,1),T=U(q(c.regressionlinecolor,f.regressionlinecolor,j)),C=g(c.regressionlinethickness,f.regressionlinethickness,
1);w=Ma(g(c.regressionlinealpha,f.regressionlinealpha,100));T=ra(T,w)}for(e=0;e<A;e+=1)if(m=d[e])if(w=r.getCleanValue(m.y),p=r.getCleanValue(m.x),y=r.getCleanValue(m.z,!0),w===null)b.data.push({y:null,x:p});else{n=!0;v=U(q(m.color,m.z<0?s:j));i=q(m.alpha,h);m=a.getPointStub(m,w,p,x,c,I);v=g(f.use3dlighting)===0?v:a.getPointColor(v,i);if(y!==null)G.zMax=G.zMax>y?G.zMax:y,G.zMin=G.zMin<y?G.zMin:y;b.data.push({y:w,x:p,z:y,displayValue:m.displayValue,toolText:m.toolText,link:m.link,marker:{enabled:o,
fillColor:v,lineColor:{FCcolor:{color:B,alpha:t}},lineWidth:l,symbol:"circle"}});this.pointValueWatcher(x,w,p,z&&E)}else b.data.push({y:null});z&&(c={type:"line",color:T,showInLegend:!1,lineWidth:C,enableMouseTracking:!1,marker:{enabled:!1},data:this.getRegressionLineSeries(E,ba,A),zIndex:0},b=[b,c])}if(!n)b.showInLegend=!1;return b},postSeriesAddition:function(a,b){a.chart.clipBubbles=g(b.chart.clipbubbles,1)},getPointStub:function(a,b,c,f,x,d){var f=f[ea],b=b===null?b:f.numberFormatter.dataLabels(b),
j,w=f.tooltipSepChar;f.showTooltip?ta(a.tooltext)!==void 0?x=pa(a.tooltext):b===null?x=!1:(f.seriesNameInToolTip&&(j=q(x&&x.seriesname)),x=j?j+w:F,x+=c?c+w:F,x+=b,x+=a.z?w+a.z:F):x=F;c=g(a.showvalue,d,f.showValues)?q(a.displayvalue,a.name,a.label)!==void 0?pa(q(a.displayvalue,a.name,a.label)):b:F;a=ta(a.link);return{displayValue:c,toolText:x,link:a}}},k.scatter);k("ssgrid",{standaloneInit:!0,defaultSeriesType:"ssgrid",rendererId:"ssgrid",chart:function(a,b){var C;var c=this.containerElement,f=this.dataObj,
x=this.chartInstance,f=Ea({},f);f.chart=f.chart||f.graph||{};delete f.graph;var d,j,w,e=0,o,m,v=[],i=f.chart,h=f.data,l=h&&h.length,f=this.smartLabel,B=this.numberFormatter,t=c.offsetHeight,n=c.offsetWidth,p={},y=0,A=0,I=(i.palette>0&&i.palette<6?i.palette:g(this.paletteIndex,1))-1,c={_FCconf:{0:{stack:{}},1:{stack:{}},x:{stack:{}},noWrap:!1,marginLeftExtraSpace:0,marginRightExtraSpace:0,marginBottomExtraSpace:0,marginTopExtraSpace:0,marimekkoTotal:0},chart:{renderTo:c,ignoreHiddenSeries:!1,events:{},
spacingTop:0,spacingRight:0,spacingBottom:0,spacingLeft:0,marginTop:0,marginRight:0,marginBottom:0,marginLeft:0,borderRadius:0,borderColor:"#000000",borderWidth:1,defaultSeriesType:"ssgrid",style:{fontFamily:q(i.basefont,"Verdana"),fontSize:Ha(i.basefontsize,20)+Pa,color:q(i.basefontcolor,Z.baseFontColor[I]).replace(/^#?([a-f0-9]+)/ig,"#$1")},plotBackgroundColor:Na},labels:{smartLabel:f},colors:["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE",
"CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],credits:{href:"http://www.fusioncharts.com?BS=FCHSEvalMark",text:u.CREDIT_STRING,enabled:this.creditLabel},legend:{enabled:!1},series:[],subtitle:{text:F},title:{text:F},tooltip:{enabled:!1},exporting:{buttons:{exportButton:{},printButton:{enabled:!1}}}},s=c[ea],G=c.colors,r=c.colors.length,z=o=j=y=0,A=e=m=0;w=x.jsVars.cfgStore;x=c.chart;ja(c.chart.style);x.events.click=this.linkClickFN;j=x.toolbar=
{button:{}};o=j.button;o.scale=g(i.toolbarbuttonscale,1.15);o.width=g(i.toolbarbuttonwidth,15);o.height=g(i.toolbarbuttonheight,15);o.radius=g(i.toolbarbuttonradius,2);o.spacing=g(i.toolbarbuttonspacing,5);o.fill=ra(q(i.toolbarbuttoncolor,"ffffff"));o.labelFill=ra(q(i.toolbarlabelcolor,"cccccc"));o.symbolFill=ra(q(i.toolbarsymbolcolor,"ffffff"));o.hoverFill=ra(q(i.toolbarbuttonhovercolor,"ffffff"));o.stroke=ra(q(i.toolbarbuttonbordercolor,"bbbbbb"));o.symbolStroke=ra(q(i.toolbarsymbolbordercolor,
"9a9a9a"));o.strokeWidth=g(i.toolbarbuttonborderthickness,1);o.symbolStrokeWidth=g(i.toolbarsymbolborderthickness,1);m=o.symbolPadding=g(i.toolbarsymbolpadding,5);o.symbolHPadding=g(i.toolbarsymbolhpadding,m);o.symbolVPadding=g(i.toolbarsymbolvpadding,m);m=j.position=q(i.toolbarposition,"tr").toLowerCase();switch(m){case "tr":case "tl":case "br":case "bl":break;default:m="tr"}o=j.hAlign=(F+i.toolbarhalign).toLowerCase()==="left"?"l":m.charAt(1);C=j.vAlign=(F+i.toolbarvalign).toLowerCase()==="bottom"?
"b":m.charAt(0),m=C;j.hDirection=g(i.toolbarhdirection,o==="r"?-1:1);j.vDirection=g(i.toolbarvdirection,m==="b"?-1:1);j.vMargin=g(i.toolbarvmargin,6);j.hMargin=g(i.toolbarhmargin,10);j.x=g(i.toolbarx,o==="l"?0:a);j.y=g(i.toolbary,m==="t"?0:b);if(q(i.clickurl)!==void 0)x.link=i.clickurl,x.style.cursor="pointer";p.showPercentValues=g(w.showpercentvalues,i.showpercentvalues,0);p.numberItemsPerPage=q(w.numberitemsperpage,i.numberitemsperpage);p.showShadow=g(w.showshadow,i.showshadow,0);p.baseFont=q(w.basefont,
i.basefont,"Verdana");d=Ha(w.basefontsize,i.basefontsize,10);p.baseFontSize=d+Pa;p.baseFontColor=U(q(w.basefontcolor,i.basefontcolor,Z.baseFontColor[I]));p.alternateRowBgColor=U(q(w.alternaterowbgcolor,i.alternaterowbgcolor,Z.altHGridColor[I]));p.alternateRowBgAlpha=q(w.alternaterowbgalpha,i.alternaterowbgalpha,Z.altHGridAlpha[I])+F;p.listRowDividerThickness=g(w.listrowdividerthickness,i.listrowdividerthickness,1);p.listRowDividerColor=U(q(w.listrowdividercolor,i.listrowdividercolor,Z.borderColor[I]));
p.listRowDividerAlpha=g(w.listrowdivideralpha,i.listrowdivideralpha,Z.altHGridAlpha[I])+15+F;p.colorBoxWidth=g(w.colorboxwidth,i.colorboxwidth,8);p.colorBoxHeight=g(w.colorboxheight,i.colorboxheight,8);p.navButtonRadius=g(w.navbuttonradius,i.navbuttonradius,7);p.navButtonColor=U(q(w.navbuttoncolor,i.navbuttoncolor,Z.canvasBorderColor[I]));p.navButtonHoverColor=U(q(w.navbuttonhovercolor,i.navbuttonhovercolor,Z.altHGridColor[I]));p.textVerticalPadding=g(w.textverticalpadding,i.textverticalpadding,3);
p.navButtonPadding=g(w.navbuttonpadding,i.navbuttonpadding,5);p.colorBoxPadding=g(w.colorboxpadding,i.colorboxpadding,10);p.valueColumnPadding=g(w.valuecolumnpadding,i.valuecolumnpadding,10);p.nameColumnPadding=g(w.namecolumnpadding,i.namecolumnpadding,5);p.borderThickness=g(w.borderthickness,i.borderthickness,1);p.borderColor=U(q(w.bordercolor,i.bordercolor,Z.borderColor[I]));p.borderAlpha=q(w.borderalpha,i.borderalpha,Z.borderAlpha[I])+F;p.bgColor=q(w.bgcolor,i.bgcolor,"FFFFFF");p.bgAlpha=q(w.bgalpha,
i.bgalpha,xa);p.bgRatio=q(w.bgratio,i.bgratio,xa);p.bgAngle=q(w.bgangle,i.bgangle,va);x.borderRadius=p.borderThickness/16;x.borderWidth=p.borderThickness;x.borderColor=L({FCcolor:{color:p.borderColor,alpha:p.borderAlpha}});x.backgroundColor={FCcolor:{color:p.bgColor,alpha:p.bgAlpha,ratio:p.bgRatio,angle:p.bgAngle}};x.borderRadius=g(i.borderradius,0);w={fontFamily:p.baseFont,fontSize:p.baseFontSize,color:p.baseFontColor};ja(w);f.setStyle(w);for(e=0;e<l;e+=1)if(d=h[e],o=B.getCleanValue(d.value),m=pa(Da(d.label,
d.name)),j=U(q(d.color,G[e%r])),q(d.alpha,i.plotfillalpha,xa),m!=F||o!=null)v.push({value:o,label:m,color:j}),y+=o,A+=1;for(e=0;e<A;e+=1)d=v[e],o=d.value,d.dataLabel=d.label,d.displayValue=p.showPercentValues?B.percentValue(o/y*100):B.dataLabels(o),h=f.getOriSize(d.displayValue),z=Math.max(z,h.width+p.valueColumnPadding);p.numberItemsPerPage?p.numberItemsPerPage>=A?(p.numberItemsPerPage=A,o=t/p.numberItemsPerPage,j=A):(B=t,B-=2*(p.navButtonPadding+p.navButtonRadius),j=p.numberItemsPerPage,o=B/j):
(y=parseInt(w.lineHeight,10),y+=2*p.textVerticalPadding,y=Math.max(y,p.colorBoxHeight),t/y>=A?(o=t/A,j=A):(B=t,B-=2*(p.navButtonPadding+p.navButtonRadius),j=Math.floor(B/y),o=B/j));m=n-p.colorBoxPadding-p.colorBoxWidth-p.nameColumnPadding-z-p.valueColumnPadding;e=p.colorBoxPadding+p.colorBoxWidth+p.nameColumnPadding;B=q(i.basefont,"Verdana");h=Ha(i.basefontsize,10);I=q(i.basefontcolor,Z.baseFontColor[I]);l=q(i.outcnvbasefont,B);d=Ha(i.outcnvbasefontsize,h);z=d+Pa;i=q(i.outcnvbasefontcolor,I).replace(/^#?([a-f0-9]+)/ig,
"#$1");h+=Pa;I=I.replace(/^#?([a-f0-9]+)/ig,"#$1");s.trendStyle=s.outCanvasStyle={fontFamily:l,color:i,fontSize:z};ja(s.trendStyle);s.inCanvasStyle={fontFamily:B,fontSize:h,color:I};c.tooltip.style={fontFamily:B,fontSize:h,lineHeight:void 0,color:I};c.tooltip.shadow=!1;x.height=t;x.width=n;x.rowHeight=o;x.labelX=e;x.colorBoxWidth=p.colorBoxWidth;x.colorBoxHeight=p.colorBoxHeight;x.colorBoxX=p.colorBoxPadding;x.valueX=p.colorBoxPadding+p.colorBoxWidth+p.nameColumnPadding+m+p.valueColumnPadding;x.valueColumnPadding=
p.valueColumnPadding;x.textStyle=w;x.listRowDividerAttr={"stroke-width":p.listRowDividerThickness,stroke:{FCcolor:{color:p.listRowDividerColor,alpha:p.listRowDividerAlpha}}};x.alternateRowColor={FCcolor:{color:p.alternateRowBgColor,alpha:p.alternateRowBgAlpha}};x.navButtonRadius=p.navButtonRadius;x.navButtonPadding=p.navButtonPadding;x.navButtonColor=p.navButtonColor;x.navButtonHoverColor=p.navButtonHoverColor;x.lineHeight=parseInt(w.lineHeight,10);i=[];t=0;p=!0;for(e=0;e<A&j!=0;e+=1)e%j==0&&(i.push({data:[],
visible:p}),p=!1,t+=1),d=v[e],n=f.getSmartText(d.dataLabel,m,o),i[t-1].data.push({label:n.text,originalText:n.tooltext,displayValue:d.displayValue,y:d.value,color:d.color});c.series=i;k.base.parseExportOptions.call(this,c);c.tooltip.enabled=!!c.exporting.enabled;return c},creditLabel:sa},k.base);k("renderer.bubble",{drawPlotBubble:function(a,d){var c=this,f=c.options,x=f.chart,h=f.plotOptions.series,j=c.paper,w=c.elements,l=a.items,o=a.graphics=a.graphics||[],m=c.xAxis[d.xAxis||0],v=c.yAxis[d.yAxis||
0],i=a.data,k=(f.tooltip||{}).enabled!==!1,h=isNaN(+h.animation)&&h.animation.duration||h.animation*1E3,t=d.visible===!1?"hidden":"visible",f=f.plotOptions.bubble,B=f.zMax,f=f.bubbleScale,A=X(c.canvasHeight,c.canvasWidth)/8,B=R(B),n,p,y,q,I,ba,G,r,z,E,T=c.layers,u=T.dataset=T.dataset||j.group("dataset-orphan");T.datalabels=T.datalabels||j.group("datalables").insertAfter(u);var T=T.tracker,C,H,u=u.bubble=u.bubble||j.group("bubble",u);x.clipBubbles&&!u.attrs["clip-rect"]&&u.attr({"clip-rect":w["clip-canvas"]});
w=0;for(n=i.length;w<n;w+=1){p=i[w];z=E=H=null;r=p.marker;if(p.y!==null&&r&&r.enabled){y=p.link;x=p.toolText;q=g(p.x,w);I=p.y;G=v.getAxisPosition(I);ba=m.getAxisPosition(q);z=R(p.z);C=s(z*A/B)*f;z=j.circle(ba,G,0,u).attr({fill:L(r.fillColor),"stroke-width":r.lineWidth,stroke:L(r.lineColor),visibility:t}).animate({r:C||0},h,"easeOut");if(y||k)C<b&&(C=b),E=j.circle(ba,G,C,T).attr({cursor:y?"pointer":"",stroke:e,"stroke-width":r.lineWidth,fill:e,ishot:!!y,visibility:t}).tooltip(x).data("link",y).click(function(){var a=
this.data("link");a&&c.linkClickFN.call({link:a},c)});l[w]={index:w,x:q,y:I,z:p.z,value:I,graphic:z,dataLabel:H,tracker:E};H=c.drawPlotLineLabel(a,d,w,ba,G)}else l[w]={index:w,x:q,y:I};H&&o.push(H);z&&o.push(z);E&&o.push(E)}a.visible=d.visible!==!1;return a}},k["renderer.cartesian"]);k("renderer.ssgrid",{drawGraph:function(){var a=this.options.series,b=this.elements,c=b.plots,f=a.length,d;if(!c)c=this.plots=this.plots||[],b.plots=c;this.drawSSGridNavButton();for(d=0;d<f;d++){if(!(b=c[d]))c.push(b=
{items:[],data:a[d].data});a[d].data&&a[d].data.length&&this.drawPlot(b,a[d])}f>1&&this.nenagitePage(0)},drawPlot:function(a){var b=a.data,c=this.paper,f=this.options.chart,x=f.colorBoxHeight,e=f.colorBoxWidth,j=f.colorBoxX,w=f.labelX,h=f.valueX,o=f.rowHeight,m=f.width,v=f.listRowDividerAttr,i=v["stroke-width"],v=L(v.stroke),l=i%2/2,k=f.textStyle,B=this.layers,B=B.dataset=B.dataset||c.group("dataset-orphan"),f=L(f.alternateRowColor),a=a.items,g=0,n,p,y,A;if(!b||!b.length)b=[];v={stroke:v,"stroke-width":i};
A=0;for(i=b.length;A<i;A+=1)if(y=b[A],p=y.y,n=a[A]={index:A,value:p,graphic:null,dataLabel:null,dataValue:null,alternateRow:null,listRowDivider:null,hot:null},!(p===null||p===void 0)){if(A%2===0)n.alternateRow=c.rect(0,g,m,o,0,B).attr({fill:f,"stroke-width":0});p=s(g)+l;n.listRowDivider=c.path([d,0,p,t,m,p],B).attr(v);n.graphic=c.rect(j,g+o/2-x/2,e,x,0,B).attr({fill:y.color,"stroke-width":0,stroke:"#000000"});p=n.dataLabel=c.text().attr({text:y.label,title:y.originalText||"",x:w,y:g+o/2,fill:k.color,
"text-anchor":"start"}).css(k);B.appendChild(p);n=n.dataValue=c.text().attr({text:y.displayValue,title:y.originalText||"",x:h,y:g+o/2,fill:k.color,"text-anchor":"start"}).css(k);B.appendChild(n);g+=o}p=s(g)+l;c.path([d,0,p,t,m,p],B).attr(v)},drawSSGridNavButton:function(a){var a=this,b=a.paper,c=a.options,f=c.chart,x=c.series,e=f.navButtonColor,j=f.navButtonHoverColor,c=f.navButtonRadius,w=c*0.67,h=f.navButtonPadding+w+(x&&x[0].data&&x[0].data.length*f.rowHeight)+c*0.5,f=f.width-20,o,m,v;if(x.length>
1){var i=a.naviigator=b.group("navigation");a.navElePrv=x=b.group(i);o=b.path([d,20,h,t,20+c+w,h-w,20+c,h,20+c+w,h+w,"Z"]).attr({fill:e,"stroke-width":0,cursor:"pointer"});x.appendChild(o);v=b.circle(20+c,h,c).attr({fill:Na,"stroke-width":0,cursor:"pointer"}).mouseover(function(){o.attr({fill:j,cursor:"pointer"})}).mouseout(function(){o.attr({fill:e})}).click(function(){a.nenagitePage(-1)});x.appendChild(v);a.navEleNxt=x=b.group(i);m=b.path([d,f,h,t,f-c-w,h-w,f-c,h,f-c-w,h+w,"Z"]).attr({fill:e,"stroke-width":0,
cursor:"pointer"});x.appendChild(m);b=b.circle(f-c,h,c).attr({fill:Na,"stroke-width":0,cursor:"pointer"}).mouseover(function(){m.attr({fill:j})}).mouseout(function(){m.attr({fill:e})}).click(function(){a.nenagitePage(1)});x.appendChild(b)}},nenagitePage:function(a){var b=this.plots,c=b.length,a=(this.currentSeriesIndex||0)+(a||0),f;if(b[a]){for(f=c;f--;)ia(b[f].items,function(a){a.graphic&&a.graphic.hide();a.dataLabel&&a.dataLabel.hide();a.dataValue&&a.dataValue.hide();a.alternateRow&&a.alternateRow.hide();
a.listRowDivider&&a.listRowDivider.hide()});ia(b[a].items,function(a){a.graphic&&a.graphic.show();a.dataLabel&&a.dataLabel.show();a.dataValue&&a.dataValue.show();a.alternateRow&&a.alternateRow.show();a.listRowDivider&&a.listRowDivider.show()});this.currentSeriesIndex=a;a===0?this.navElePrv.hide():this.navElePrv.show();a===c-1?this.navEleNxt.hide():this.navEleNxt.show()}}},k["renderer.root"]);na.prototype={getArcPath:function(a,b,c,f,d,e,j,w,l,o){return c==d&&f==e?[]:[h,j,w,0,o,l,d,e]},parseColor:function(a,
b){var c,f,d,e,j,w,h,o,m,v,i=b/2,l,k,t,g,n;n=3;this.use3DLighting?(c=ca(a,80),f=ca(a,75),w=ka(a,85),h=ka(a,70),o=ka(a,40),m=ka(a,50),ka(a,30),v=ka(a,65),ca(a,85),d=ca(a,69),e=ca(a,75),j=ca(a,95)):(n=10,c=ca(a,90),f=ca(a,87),w=ka(a,93),h=ka(a,87),o=ka(a,80),v=m=ka(a,85),ka(a,80),j=ca(a,85),d=ca(a,75),e=ca(a,80));l=f+J+w+J+h+J+w+J+f;t=b+J+b+J+b+J+b+J+b;k=f+J+a+J+w+J+a+J+f;g=i+J+i+J+i+J+i+J+i;o=f+J+a+J+o+J+a+J+f;d=e+J+w+J+m+J+w+J+d;e="FFFFFF"+J+"FFFFFF"+J+"FFFFFF"+J+"FFFFFF"+J+"FFFFFF";n=0+J+i/n+J+b/
n+J+i/n+J+0;return{frontOuter:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftX,y1:0,x2:this.rightX,y2:0,color:d,alpha:t,angle:0,ratio:"0,20,15,15,50"}},backOuter:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftX,y1:0,x2:this.rightX,y2:0,color:o,alpha:g,angle:0,ratio:"0,62,8,8,22"}},frontInner:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftInnerX,y1:0,x2:this.rightInnerX,y2:0,color:k,alpha:g,angle:0,ratio:"0,25,5,5,65"}},backInner:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftInnerX,
y1:0,x2:this.rightInnerX,y2:0,color:l,alpha:t,angle:0,ratio:"0,62,8,8,22"}},topBorder:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftX,y1:0,x2:this.rightX,y2:0,color:e,alpha:n,angle:0,ratio:"0,20,15,15,50"}},topInnerBorder:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftInnerX,y1:0,x2:this.rightInnerX,y2:0,color:e,alpha:n,angle:0,ratio:"0,50,15,15,20"}},top:Y?{FCcolor:{gradientUnits:"userSpaceOnUse",radialGradient:!0,cx:this.cx,cy:this.cy,r:this.rx,fx:this.cx-0.3*this.rx,fy:this.cy+this.ry*
1.2,color:v+J+j,alpha:b+J+b,ratio:"0,100"}}:{FCcolor:{gradientUnits:"objectBoundingBox",color:h+J+h+J+w+J+f,alpha:b+J+b+J+b+J+b,angle:-72,ratio:"0,8,15,77"}},bottom:L(ra(a,i)),startSlice:L(ra(c,b)),endSlice:L(ra(c,b))}},rotate:function(a){if(!this.hasOnePoint){for(var b=this.pointElemStore,c=0,f=b.length,d;c<f;c+=1)d=b[c],d=d._confObject,d.start+=a,d.end+=a,this.updateSliceConf(d);this.refreshDrawing()}},refreshDrawing:function(){return function(){var a=this.slicingWallsArr,b=0,c,f=a.length,d,e,j,
w,h=this.slicingWallsFrontGroup,o=this.slicingWallsBackGroup;a:{var m=a[0]&&a[0]._conf.index,v,i;w=m<=O;d=1;for(c=a.length;d<c;d+=1)if(i=a[d]._conf.index,v=i<=O,v!=w||i<m)break a;d=0}for(;b<f;b+=1,d+=1)d===f&&(d=0),c=a[d],w=c._conf.index,w<fa?h.appendChild(c):w<=O?(e?c.insertBefore(e):h.appendChild(c),e=c):w<V?(j?c.insertBefore(j):o.appendChild(c),j=c):o.appendChild(c)}}(),updateSliceConf:function(a,b){var c=this.getArcPath,f=a.start,e=a.end,l=wa(f),j=wa(e),w,k,o,m,v,i,g,n,B,q,s,p,y,u,I,J,G=this.cx,
r=this.cy,z=this.rx,E=this.ry,Q=z+(Y?-1:2),M=E+(Y?-1:2),C=this.innerRx,H=this.innerRy,N=this.depth,P=this.depthY,X=a.elements,D,S,aa,R;w=T(l);k=ba(l);o=T(j);m=ba(j);v=G+z*w;i=r+E*k;g=G+Q*w;n=r+M*k;D=i+N;S=G+z*o;aa=r+E*m;B=G+Q*o;q=r+M*m;R=aa+N;this.isDoughnut?(s=G+C*w,p=r+H*k,I=p+N,y=G+C*o,u=r+H*m,J=u+N,a.startSlice=[d,v,i,t,v,D,s,I,s,p,A],a.endSlice=[d,S,aa,t,S,R,y,J,y,u,A]):(a.startSlice=[d,v,i,t,v,D,G,P,G,r,A],a.endSlice=[d,S,aa,t,S,R,G,P,G,r,A]);if(Y){c=(l>j?ga:0)+j-l;a.clipTopPath=this.isDoughnut?
[d,v,i,h,z,E,0,c>O?1:0,1,S,aa,t,y,u,h,C,H,0,c>O?1:0,0,s,p,A]:[d,v,i,h,z,E,0,c>O?1:0,1,S,aa,t,this.cx,this.cy,A];a.clipOuterFrontPath1=this.clipPathforNoClip;a.clipTopBorderPath=[d,g,n,h,Q,M,0,c>O?1:0,1,B,q,t,S,aa,S,aa+1,h,z,E,0,c>O?1:0,0,v,i+1,t,v,i,A];if(f!=e)if(l>j)if(l<O){if(a.clipOuterFrontPath=[d,this.rightX,r,h,z,E,0,0,1,S,aa,"v",N,h,z,E,0,0,0,this.rightX,r+N,A],a.clipOuterFrontPath1=[d,this.leftX,r,h,z,E,0,0,0,v,i,"v",N,h,z,E,0,0,1,this.leftX,r+N,A],a.clipOuterBackPath=[d,this.rightX,r,h,z,
E,0,1,0,this.leftX,r,"v",N,h,z,E,0,1,1,this.rightX,r+N,A],this.isDoughnut)a.clipInnerBackPath=[d,this.rightInnerX,r,h,C,H,0,1,0,this.leftInnerX,r,"v",N,h,C,H,0,1,1,this.rightInnerX,r+N,A],a.clipInnerFrontPath=[d,this.rightInnerX,r,h,C,H,0,0,1,y,u,"v",N,h,C,H,0,0,0,this.rightInnerX,r+N,A,d,this.leftInnerX,r,h,C,H,0,0,0,s,p,"v",N,h,C,H,0,0,1,this.leftInnerX,r+N,A]}else if(j>O){if(a.clipOuterFrontPath=[d,this.rightX,r,h,z,E,0,1,1,this.leftX,r,"v",N,h,z,E,0,1,0,this.rightX,r+N,A],a.clipOuterBackPath=
[d,this.leftX,r,h,z,E,0,0,1,S,aa,"v",N,h,z,E,0,0,0,this.leftX,r+N,A,d,this.rightX,r,h,z,E,0,0,0,v,i,"v",N,h,z,E,0,0,1,this.rightX,r+N,A],this.isDoughnut)a.clipInnerFrontPath=[d,this.rightInnerX,r,h,C,H,0,1,1,this.leftInnerX,r,"v",N,h,C,H,0,1,0,this.rightInnerX,r+N,A],a.clipInnerBackPath=[d,this.leftInnerX,r,h,C,H,0,0,1,y,u,"v",N,h,C,H,0,0,0,this.leftInnerX,r+N,A,d,this.rightInnerX,r,h,C,H,0,0,0,s,p,"v",N,h,C,H,0,0,1,this.rightInnerX,r+N,A]}else{if(a.clipOuterFrontPath=[d,this.rightX,r,h,z,E,0,0,1,
S,aa,"v",N,h,z,E,0,0,0,this.rightX,r+N,A],a.clipOuterBackPath=[d,v,i,h,z,E,0,0,1,this.rightX,r,"v",N,h,z,E,0,0,0,v,D,A],this.isDoughnut)a.clipInnerFrontPath=[d,this.rightInnerX,r,h,C,H,0,0,1,y,u,"v",N,h,C,H,0,0,0,this.rightInnerX,r+N,A],a.clipInnerBackPath=[d,s,p,h,C,H,0,0,1,this.rightInnerX,r,"v",N,h,C,H,0,0,0,s,I,A]}else if(l<O)if(j>O){if(a.clipOuterFrontPath=[d,v,i,h,z,E,0,0,1,this.leftX,r,"v",N,h,z,E,0,0,0,v,D,A],a.clipOuterBackPath=[d,this.leftX,r,h,z,E,0,0,1,S,aa,"v",N,h,z,E,0,0,0,this.leftX,
r+N,A],this.isDoughnut)a.clipInnerFrontPath=[d,s,p,h,C,H,0,0,1,this.leftInnerX,r,"v",N,h,C,H,0,0,0,s,I,A],a.clipInnerBackPath=[d,this.leftInnerX,r,h,C,H,0,0,1,y,u,"v",N,h,C,H,0,0,0,this.leftInnerX,r+N,A]}else{if(a.clipOuterFrontPath=[d,v,i,h,z,E,0,0,1,S,aa,"v",N,h,z,E,0,0,0,v,D,A],a.clipOuterBackPath=this.clipPathforNoClip,this.isDoughnut)a.clipInnerFrontPath=[d,s,p,h,C,H,0,0,1,y,u,"v",N,h,C,H,0,0,0,s,I,A],a.clipInnerBackPath=this.clipPathforNoClip}else{if(a.clipOuterFrontPath=this.clipPathforNoClip,
a.clipOuterBackPath=[d,v,i,h,z,E,0,0,1,S,aa,"v",N,h,z,E,0,0,0,v,D,A],this.isDoughnut)a.clipInnerFrontPath=this.clipPathforNoClip,a.clipInnerBackPath=[d,s,p,h,C,H,0,0,1,y,u,"v",N,h,C,H,0,0,0,s,I,A]}else a.clipOuterFrontPath=a.clipOuterBackPath=a.clipInnerBackPath=a.clipInnerFrontPath=this.clipPathforNoClip;if(!b){a.elements.startSlice._conf.index=l;a.elements.endSlice._conf.index=j;a.elements.frontOuter._conf.index=ya(j,l);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=l,a.elements.frontOuter1.attr("litepath",
[a.clipOuterFrontPath1]);a.thisElement.attr("litepath",[a.clipTopPath]);a.elements.bottom.attr("litepath",[a.clipTopPath]);a.elements.bottomBorder.attr("litepath",[a.clipTopPath]);a.elements.topBorder&&a.elements.topBorder.attr("litepath",[a.clipTopBorderPath]);a.elements.frontOuter.attr("litepath",[a.clipOuterFrontPath]);a.elements.backOuter.attr("litepath",[a.clipOuterBackPath]);if(this.isDoughnut)a.elements.backInner.attr("litepath",[a.clipInnerBackPath]),a.elements.frontInner.attr("litepath",
[a.clipInnerFrontPath]),a.elements.backInner._conf.index=ya(j,l);this.hasOnePoint?(a.elements.startSlice.hide(),a.elements.endSlice.hide()):(a.elements.startSlice.attr("litepath",[a.startSlice]).show(),a.elements.endSlice.attr("litepath",[a.endSlice]).show())}}else{g=this.moveCmdArr;n=this.lineCmdArr;B=this.closeCmdArr;var F=this.centerPoint;q=this.leftPoint;var Q=this.topPoint,M=this.rightPoint,N=this.bottomPoint,V=this.leftDepthPoint,U=this.rightDepthPoint;w=this.leftInnerPoint;k=this.rightInnerPoint;
o=this.leftInnerDepthPoint;m=this.rightInnerDepthPoint;a.clipOuterFrontPath1=[];if(f!=e){if(l>j?l<O?(f=c(G,r,v,i,this.leftX,r,z,E,1,0),e=c(G,r,this.leftX,r,this.rightX,r,z,E,1,0),aa=c(G,r,this.rightX,r,S,aa,z,E,1,0),a.clipOuterBackPath=g.concat(q,e,n,U,c(G,P,this.rightX,P,this.leftX,P,z,E,0,0),B),a.clipOuterFrontPath1=g.concat([v,i],f,n,V,c(G,P,this.leftX,P,v,D,z,E,0,0),B),a.clipOuterFrontPath=g.concat(M,aa,n,[S,R],c(G,P,S,R,this.rightX,P,z,E,0,0),B),a.clipTopBorderPath=g.concat([v,i],f,e,aa),this.isDoughnut?
(v=c(G,r,y,u,this.rightInnerX,r,C,H,0,0),i=c(G,r,this.rightInnerX,r,this.leftInnerX,r,C,H,0,0),p=c(G,r,this.leftInnerX,r,s,p,C,H,0,0),a.clipInnerBackPath=g.concat(k,i,n,o,c(G,P,this.leftInnerX,P,this.rightInnerX,P,C,H,1,0),B),a.clipInnerFrontPath=g.concat(w,p,n,[s,I],c(G,P,s,I,this.leftInnerX,P,C,H,1,0),B,g,[y,u],v,n,m,c(G,P,this.rightInnerX,P,y,J,C,H,1,0),B),a.clipTopPath=a.clipTopBorderPath.concat(n,[y,u],v,i,p,B),a.clipTopBorderPath=a.clipTopBorderPath.concat(g,[y,u],v,i,p)):a.clipTopPath=a.clipTopBorderPath.concat(n,
F,B)):j>O?(f=c(G,r,v,i,this.rightX,r,z,E,1,0),e=c(G,r,this.rightX,r,this.leftX,r,z,E,1,0),aa=c(G,r,this.leftX,r,S,aa,z,E,1,0),a.clipOuterFrontPath=g.concat(M,e,n,V,c(G,P,this.leftX,P,this.rightX,P,z,E,0,0),B),a.clipOuterBackPath=g.concat([v,i],f,n,U,c(G,P,this.rightX,P,v,D,z,E,0,0),B,g,q,aa,n,[S,R],c(G,P,S,R,this.leftX,P,z,E,0,0),B),a.clipTopBorderPath=g.concat([v,i],f,e,aa),this.isDoughnut?(v=c(G,r,y,u,this.leftInnerX,r,C,H,0,0),i=c(G,r,this.leftInnerX,r,this.rightInnerX,r,C,H,0,0),p=c(G,r,this.rightInnerX,
r,s,p,C,H,0,0),a.clipInnerFrontPath=g.concat(w,i,n,m,c(G,P,this.rightInnerX,P,this.leftInnerX,P,C,H,1,0),B),a.clipInnerBackPath=g.concat(k,p,n,[s,I],c(G,P,s,I,this.rightInnerX,P,C,H,1,0),B,g,[y,u],v,n,o,c(G,P,this.leftInnerX,P,y,J,C,H,1,0),B),a.clipTopPath=a.clipTopBorderPath.concat(n,[y,u],v,i,p,B),a.clipTopBorderPath=a.clipTopBorderPath.concat(g,[y,u],v,i,p)):a.clipTopPath=a.clipTopBorderPath.concat(n,F,B)):(f=c(G,r,v,i,this.rightX,r,z,E,1,0),e=c(G,r,this.rightX,r,S,aa,z,E,1,0),a.clipOuterFrontPath=
g.concat(M,e,n,[S,R],c(G,P,S,R,this.rightX,P,z,E,0,0),B),a.clipOuterBackPath=g.concat([v,i],f,n,U,c(G,P,this.rightX,P,v,D,z,E,0,0),B),a.clipTopBorderPath=g.concat([v,i],f,e),this.isDoughnut?(v=c(G,r,y,u,this.rightInnerX,r,C,H,0,0),i=c(G,r,this.rightInnerX,r,s,p,C,H,0,0),a.clipInnerFrontPath=g.concat([y,u],v,n,m,c(G,P,this.rightInnerX,P,y,J,C,H,1,0),B),a.clipInnerBackPath=g.concat(k,i,n,[s,I],c(G,P,s,I,this.rightInnerX,P,C,H,1,0),B),a.clipTopPath=a.clipTopBorderPath.concat(n,[y,u],v,i,B),a.clipTopBorderPath=
a.clipTopBorderPath.concat(g,[y,u],v,i)):a.clipTopPath=a.clipTopBorderPath.concat(n,F,B)):l<O?j>O?(f=c(G,r,v,i,this.leftX,r,z,E,1,0),e=c(G,r,this.leftX,r,S,aa,z,E,1,0),a.clipOuterBackPath=g.concat(q,e,n,[S,R],c(G,P,S,R,this.leftX,P,z,E,0,0),B),a.clipOuterFrontPath=g.concat([v,i],f,n,V,c(G,P,this.leftX,P,v,D,z,E,0,0),B),a.clipTopBorderPath=g.concat([v,i],f,e),this.isDoughnut?(v=c(G,r,y,u,this.leftInnerX,r,C,H,0,0),i=c(G,r,this.leftInnerX,r,s,p,C,H,0,0),a.clipInnerBackPath=g.concat([y,u],v,n,o,c(G,
P,this.leftInnerX,P,y,J,C,H,1,0),B),a.clipInnerFrontPath=g.concat(w,i,n,[s,I],c(G,P,s,I,this.leftInnerX,P,C,H,1,0),B),a.clipTopPath=a.clipTopBorderPath.concat(n,[y,u],v,i,B),a.clipTopBorderPath=a.clipTopBorderPath.concat(g,[y,u],v,i)):a.clipTopPath=a.clipTopBorderPath.concat(n,F,B)):(f=c(G,r,v,i,S,aa,z,E,1,0),a.clipOuterBackPath=g.concat([v,i]),a.clipTopBorderPath=a.clipOuterBackPath.concat(f),a.clipOuterFrontPath=a.clipTopBorderPath.concat(n,[S,R],c(G,P,S,R,v,D,z,E,0,0),B),this.isDoughnut?(v=c(G,
r,y,u,s,p,C,H,0,0),a.clipInnerBackPath=g.concat([y,u]),a.clipTopPath=a.clipTopBorderPath.concat(n,[y,u],v,B),a.clipTopBorderPath=a.clipTopBorderPath.concat(g,[y,u],v),a.clipInnerFrontPath=a.clipInnerBackPath.concat(v,n,[s,I],c(G,P,s,I,y,J,C,H,1,0),B)):a.clipTopPath=a.clipTopBorderPath.concat(n,F,B)):(f=c(G,r,v,i,S,aa,z,E,1,0),a.clipOuterFrontPath=g.concat([v,i]),a.clipTopBorderPath=a.clipOuterFrontPath.concat(f),a.clipOuterBackPath=a.clipTopBorderPath.concat(n,[S,R],c(G,P,S,R,v,D,z,E,0,0),B),this.isDoughnut?
(v=c(G,r,y,u,s,p,C,H,0,0),a.clipInnerFrontPath=g.concat([y,u]),a.clipTopPath=a.clipTopBorderPath.concat(n,[y,u],v,B),a.clipTopBorderPath=a.clipTopBorderPath.concat(a.clipInnerFrontPath,v),a.clipInnerBackPath=a.clipInnerFrontPath.concat(v,n,[s,I],c(G,P,s,I,y,J,C,H,1,0),B)):a.clipTopPath=a.clipTopBorderPath.concat(n,F,B)),f=g.concat(q,n,M),v=g.concat(Q,n,N),a.clipTopPath=a.clipTopPath.concat(f,v),a.clipOuterFrontPath=a.clipOuterFrontPath.concat(f),a.clipOuterFrontPath1=a.clipOuterFrontPath1.concat(f),
a.clipOuterBackPath=a.clipOuterBackPath.concat(f),this.isDoughnut)v=g.concat(w,n,k),a.clipInnerFrontPath=a.clipInnerFrontPath.concat(v),a.clipInnerBackPath=a.clipInnerBackPath.concat(v)}else if(a.clipTopPath=a.clipOuterFrontPath=a.clipOuterBackPath=[],this.isDoughnut)a.clipInnerFrontPath=a.clipInnerBackPath=[];if(!b){a.elements.startSlice._conf.index=l;a.elements.endSlice._conf.index=j;a.elements.frontOuter._conf.index=ya(j,l);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=l,X.frontOuter1.attr({path:a.clipOuterFrontPath1});
a.thisElement.attr({path:a.clipTopPath});X.topBorder.attr({path:a.clipTopBorderPath});X.bottom.attr({path:a.clipTopPath});X.bottomBorder.attr({path:a.clipTopBorderPath});X.frontOuter.attr({path:a.clipOuterFrontPath});X.backOuter.attr({path:a.clipOuterBackPath});this.isDoughnut&&(X.frontInner.attr({path:a.clipInnerFrontPath}),X.backInner.attr({path:a.clipInnerBackPath}));this.hasOnePoint?(a.elements.startSlice.hide(),a.elements.endSlice.hide()):(a.elements.startSlice.attr({path:a.startSlice}).show(),
a.elements.endSlice.attr({path:a.endSlice}).show())}}},createSlice:function(){var a={stroke:!0,strokeWidth:!0,"stroke-width":!0,dashstyle:!0,"stroke-dasharray":!0,translateX:!0,translateY:!0,"stroke-opacity":!0,transform:!0,fill:!0,opacity:!0,ishot:!0,start:!0,end:!0,cursor:!0},b=function(b,c){var f,d,e=this,h=e._confObject,i,l=h.elements,x,g,n=h.pie3DManager;typeof b==="string"&&c!==void 0&&c!==null&&(f=b,b={},b[f]=c);if(!b||typeof b==="string")e=e._attr(b);else{if(b.cx!==void 0)b.start=b.cx;if(b.cy!==
void 0)b.end=b.cy;for(f in b)if(d=b[f],a[f])if(h[f]=d,f==="ishot"||f==="cursor"){i={};i[f]=d;for(x in l)l[x].attr(i);e._attr(i)}else if(f==="transform"){for(x in l)l[x].attr({transform:b[f]});e._attr({transform:b[f]})}else if(f==="stroke"||f==="strokeWidth"||f==="stroke-width"||f==="dashstyle"||f==="stroke-dasharray")i={},i[f]=d,l.topBorder&&l.topBorder.attr(i),l.startSlice.attr(i),l.endSlice.attr(i),l.bottomBorder.attr(i);else{if(f!=="fill"&&(f==="start"||f==="end"))g=!0}else e._attr(f,d);g&&(n.updateSliceConf(h),
n.refreshDrawing())}return e},c=function(a,b,c,f){var d=this._confObject.elements,e;for(e in d)if(c)d[e].drag(b,c,f);else d[e].on(a,b);return c?this.drag(b,c,f):this._on(a,b)},f=function(){var a=this._confObject.elements,b;for(b in a)a[b].hide();return this._hide()},d=function(){var a=this._confObject.elements,b;for(b in a)a[b].show();return this._show()},e=function(){var a=this._confObject,b=a.elements,c;for(c in b)b[c].destroy();Y&&(a.clipTop.destroy(),a.clipOuterFront.destroy(),a.clipOuterBack.destroy(),
a.clipOuterFront1&&a.clipOuterFront1.destroy(),a.clipInnerFront&&a.clipInnerFront.destroy(),a.clipInnerBack&&a.clipInnerBack.destroy());return this._destroy()};return function(a,h,l,o,m,g,i,n,k){var t=this.renderer,l=this.parseColor(l,o),s,a={start:a,end:h,elements:{},pie3DManager:this},h=this.slicingWallsArr,o=a.elements,A,p=Y?"litepath":"path";this.updateSliceConf(a,!0);if(Y){s={fill:L(l.top),"stroke-width":0};if(k!==1)s.stroke=m,s["stroke-width"]=g;s=t[p](a.clipTopPath,this.topGroup).attr(s);if(k)o.topBorder=
t[p](a.clipTopBorderPath,this.topGroup).attr({fill:L(l.topBorder),"stroke-width":0})}else s=t[p](a.clipTopPath,this.topGroup).attr({fill:L(l.top),"stroke-width":0}),o.topBorder=t[p](a.clipTopBorderPath,this.topGroup).attr({stroke:m,"stroke-width":g});o.bottom=t[p](a.clipTopPath,this.bottomBorderGroup).attr({fill:L(l.bottom),"stroke-width":0});o.bottomBorder=t[p](a.clipTopBorderPath,this.bottomBorderGroup).attr({stroke:m,"stroke-width":g});o.frontOuter=t[p](a.clipOuterFrontPath,this.slicingWallsFrontGroup).attr({fill:L(l.frontOuter),
"stroke-width":0});o.backOuter=t[p](a.clipOuterBackPath,this.outerBackGroup).attr({fill:L(l.backOuter),"stroke-width":0});o.startSlice=t[p](a.startSlice,this.slicingWallsFrontGroup).attr({fill:L(l.startSlice),stroke:m,"stroke-width":g});o.endSlice=t[p](a.endSlice,this.slicingWallsFrontGroup).attr({fill:L(l.endSlice),stroke:m,"stroke-width":g});m=wa(a.start);g=wa(a.end);k=(m>g?ga:0)+g-m;if(k>O&&(o.frontOuter1=t[p](a.clipOuterFrontPath1,this.slicingWallsFrontGroup).attr({fill:L(l.frontOuter),"stroke-width":0}),
o.frontOuter1._conf={index:m,isStart:0.5,pIndex:i},Y))a.clipOuterFront1=a.clipOuterFrontPath1;o.frontOuter._conf={index:ya(g,m),isStart:0.5,pIndex:i};o.startSlice._conf={index:m,isStart:0,pIndex:i};o.endSlice._conf={index:g,isStart:1,pIndex:i};this.hasOnePoint&&(o.startSlice.hide(),o.endSlice.hide());this.isDoughnut?(o.frontInner=t[p](a.clipInnerFrontPath,this.innerFrontGroup).attr({fill:L(l.frontInner),"stroke-width":0}),o.backInner=t[p](a.clipInnerBackPath,this.innerBackGroup).attr({fill:L(l.backInner),
"stroke-width":0}),o.backInner._conf={index:ya(g,m),isStart:0.5,pIndex:i},k>O?Y?h.push(o.startSlice,o.frontOuter1,o.frontOuter,o.backInner,o.endSlice):h.push(o.startSlice,o.frontOuter1,o.frontOuter,o.endSlice):Y?h.push(o.startSlice,o.frontOuter,o.backInner,o.endSlice):h.push(o.startSlice,o.frontOuter,o.endSlice)):k>O?h.push(o.startSlice,o.frontOuter1,o.frontOuter,o.endSlice):h.push(o.startSlice,o.frontOuter,o.endSlice);if(n!==void 0){for(A in o)o[A].tooltip(n);s.tooltip(n)}if(Y&&(a.clipTop=a.clipTopPath,
a.clipOuterFront=a.clipOuterFrontPath,a.clipOuterBack=a.clipOuterBackPath,this.isDoughnut))a.clipInnerFront=a.clipInnerFrontPath,a.clipInnerBack=a.clipInnerBackPath;s._confObject=a;a.thisElement=s;s._destroy=s.destroy;s.destroy=e;s._show=s.show;s.show=d;s._hide=s.hide;s.hide=f;s._on=s.on;s.on=c;s._attr=s.attr;s.attr=b;this.pointElemStore.push(s);return s}}()};na.prototype.constructor=na;k("renderer.pie3d",{type:"pie3d",translate:function(){var a=0,b=this.options,c=b.series[0],f=b.plotOptions.series.dataLabels,
d=b.plotOptions.pie3d,e=q(c.startAngle,0)%360,j=c.managedPieSliceDepth,h=c.slicedOffset=d.slicedOffset,l=this.canvasWidth,o=this.canvasHeight,m=[this.canvasLeft+l*0.5,this.canvasTop+o*0.5-j*0.5],k,i,t,A,B,b=c.data,u,J=X(l,o),p,y,M,I=f.distance,Q=c.pieYScale,G=c.pieSliceDepth,r=c.slicedOffsetY=h*Q;m.push(d.size,d.innerSize||0);m=ha(m,function(a,b){return(p=/%$/.test(a))?[l,o-j,J,J][b]*parseInt(a,10)/100:a});m[2]/=2;m[3]/=2;m.push(m[2]*Q);m.push((m[2]+m[3])/2);m.push(m[5]*Q);c.getX=function(a,b){t=
n.asin((a-m[1])/(m[2]+I));return m[0]+(b?-1:1)*T(t)*(m[2]+I)};c.center=m;ia(b,function(b){a+=b.y});c.labelsRadius=m[2]+I;c.labelsRadiusY=c.labelsRadius*Q;c.quadrantHeight=(o-j)/2;c.quadrantWidth=l/2;A=-e*qa;A=s(A*1E3)/1E3;B=A+ga;d=g(parseInt(f.style.fontSize,10),10)+4;c.maxLabels=oa(c.quadrantHeight/d);c.labelFontSize=d;c.connectorPadding=g(f.connectorPadding,5);c.isSmartLineSlanted=q(f.isSmartLineSlanted,!0);c.connectorWidth=g(f.connectorWidth,1);c.enableSmartLabels=f.enableSmartLabels;if(!c.pie3DManager)c.pie3DManager=
new na(m[0],m[1],m[2],m[3],Q,G,this.layers.dataset,this.paper,c.data.length===1,c.use3DLighting);ia(b,function(b){k=A;u=a?b.y/a:0;A=s((A+u*ga)*1E3)/1E3;A>B&&(A=B);i=A;b.shapeArgs={start:s(k*1E3)/1E3,end:s(i*1E3)/1E3};b.centerAngle=t=(i+k)/2%ga;b.slicedTranslation=[s(T(t)*h),s(ba(t)*r)];y=T(t)*m[2];c.radiusY=M=ba(t)*m[4];b.tooltipPos=[m[0]+y*0.7,m[1]+M];b.percentage=u*100;b.total=a})},drawPlotPie3d:function(a,b){this.translate();var c=this,f=a.items,d=a.data,e=c.options,j=e.plotOptions,h=j.series,
l=c.layers,o=c.elements.plots[0],m=c.datasets[0],j=j.series.dataLabels,n=h.dataLabels.style,h=g(a.moveDuration,h.animation.duration),i=c.paper,e=(e=e.tooltip||{})&&e.enabled!==!1,k,t=m.slicedOffset,s=m.slicedOffsetY,A=c.plotGraphicClick,q=c.plotDragMove,p=c.plotDragStart,y=c.plotDragEnd,u=c.plotMouseDown,I=c.plotMouseUp,J=!!c.datasets[0].enableRotation,G=b.showBorderEffect,r,z,E,Q,M,C,H,N,P,D,X;if(!d||!d.length)d=[];o.singletonCase=d.length==1;o.chartPosition=Aa(c.container);o.pieCenter=m.center;
o.timerThreshold=30;for(X=-1;++X<d.length;)if(z=d[X],E=z.y,Q=z.displayValue,C=z.sliced,D=z.shapeArgs,N=z.centerAngle,k=z.toolText,H=(M=!!z.link)||J||!z.doNotSlice,!(E===null||E===void 0))if(!(r=f[X])){b.data[X].plot=r=f[X]={chart:c,index:X,seriesData:o,value:E,angle:N,link:z.link,shapeArgs:D,slicedX:C&&!o.singletonCase?T(N)*t:0,slicedY:C&&!o.singletonCase?ba(N)*s:0,sliced:C,labelText:Q,graphic:m.pie3DManager.createSlice(D.start,D.end,z.color,z._3dAlpha,z.borderColor,z.borderWidth,X,e?k:"",G)};b.data[X].legendClick=
function(a){return function(){c.legendClick(null,c,a)}}(X);r.graphic.plotItem=r;r.transX=T(N)*t;r.transY=ba(N)*s;r.slicedTranslation="t"+r.transX+","+r.transY;r.graphic.attr({transform:"t"+r.slicedX+","+r.slicedY,ishot:H,cursor:M?"pointer":""});if(!z.doNotSlice)r.graphic.on("click",function(a){return function(){A.call(a)}}(r));r.graphic.on("drag",function(a){return function(b,c,f,d,e){q.call(a,b,c,f,d,e)}}(r),function(a){return function(b,c,f){p.call(a,b,c,f)}}(r),function(a){return function(){y.call(a)}}(r));
r.graphic.on("mousedown",function(a){return function(){u.call(a)}}(r));r.graphic.on("mouseup",function(a){return function(){I.call(a)}}(r));if(Q!==void 0&&(r.dataLabel=i.text(l.dataset).css(n).attr({text:Q,title:z.originalText||"",fill:n.color||"#000000",visibility:"hidden",ishot:H,cursor:M?"pointer":""}),r.dataLabel.click(A,r),r.dataLabel.mousedown(u,r),r.dataLabel.mouseup(I,r),j.distance>0&&(P=j.connectorWidth)&&j.enableSmartLabels))r.connector=i.path("M 0 0 l 0 0",l.dataset).attr({"stroke-width":P,
stroke:j.connectorColor||"#606060",visibility:"hidden",ishot:H,cursor:M?"pointer":""}),r.connector.click(A,r),r.connector.mousedown(u,r),r.connector.mouseup(I,r)}m.pie3DManager.refreshDrawing();h>0?c.animate(f,h):c.placeDataLabels(!1,f)},rotate:function(a){var b=this.datasets[0],c=this.elements.plots[0].items,f=b.slicedOffset,d=b.slicedOffsetY,e=b.startAngle,j,a=a||-b._lastAngle;j=(a-e)%360;b.startAngle=g(a,b.startAngle)%360;j=-(j*W)/180;b.pie3DManager&&b.pie3DManager.rotate(j);ia(c,function(a){var b=
a.graphic,c=a.shapeArgs,c={start:c.start+=j,end:c.end+=j},e=a.angle=wa((c.start+c.end)/2),c=a.sliced,h=T(e),e=ba(e);a.slicedTranslation=[s(h*f),s(e*d)];a.transX=a.slicedTranslation[0];a.transY=a.slicedTranslation[1];a.slicedX=c?T(j)*f:0;a.slicedY=c?ba(j)*d:0;b&&c&&a.graphic.attr({transform:"t"+a.slicedTranslation[0]+","+a.slicedTranslation[1]})});this.placeDataLabels(!0,c)},plotMouseDown:function(){this.seriesData.isRotating=!1},plotMouseUp:function(){var a=this.chart,b=this.seriesData;!b.isRotating&&
a.linkClickFN.call({link:b.data[this.index].link},a);D._supportsTouch&&!b.isRotating&&a.plotGraphicClick.call(this)},plotDragStart:function(a,b,c){var f=this.seriesData,d=this.chart.datasets[0];if(d.enableRotation)a=Ja.call(c,a,b,f.pieCenter,f.chartPosition,d.pieYScale),d.dragStartAngle=a,d._lastAngle=-d.startAngle},plotDragEnd:function(){var a=this.chart,b={hcJSON:{series:[{startAngle:a.datasets[0].startAngle}]}};a.disposed||Ea(a.logic.chartInstance.jsVars._reflowData,b,!0)},plotDragMove:function(a,
b,c,f,d){var e=this.chart,a=e.datasets[0],b=this.seriesData;if(e.options.series[0].enableRotation&&!b.singletonCase&&(b.isRotating=!0,c=Ja.call(d,c,f,b.pieCenter,b.chartPosition,a.pieYScale),f=c-a.dragStartAngle,a.dragStartAngle=c,b.moveDuration=0,a._lastAngle+=f*180/W,c=(new Date).getTime(),!a._lastTime||a._lastTime+b.timerThreshold<c))a._lastTime||e.rotate(),b.timerId=setTimeout(function(){(!e.disposed||!e.disposing)&&e.rotate()},b.timerThreshold),a._lastTime=c},animate:function(a,b){var c,d,e,
h=a.length,j,l,g,o=this,m;if(o.datasets[0].alphaAnimation)o.layers.dataset.attr({opacity:0}),o.layers.dataset.animate({opacity:1},b,"ease-in",function(){!o.disposed&&!o.disposing&&o.placeDataLabels(!1,a)});else for(c=0;c<h;c++)if(j=a[c],l=j.graphic,g=j.shapeArgs,j=2*W,l)l.attr({start:j,end:j}),m=g.start,g=g.end,d?l.animateWith(d,e,{cx:m-j,cy:g-j},b,"ease-in"):(e=D.animation({cx:m-j,cy:g-j},b,"ease-in",function(){!o.disposed&&!o.disposing&&o.placeDataLabels(!1,a)}),d=l.animate(e))},plotGraphicClick:function(){var a=
this.seriesData,b=this.chart,c,d,e,h,l,g;if(!a.isRotating&&!a.singletonCase)return c=this.graphic,d=this.connector,e=this.dataLabel,a=this.sliced,h=this.connectorPath,l=(a?-1:1)*this.transX,g=(a?-1:1)*this.transY,c.animate({transform:a?"t0,0":"t"+l+","+g},200,"easeIn"),e&&e.x&&e.animate({x:e.x+(a?0:l)},200,"easeIn"),h&&(h[1]+=l,h[2]+=g,h[4]+=l,h[6]+=l,d.animate({path:h},200,"easeIn")),a=this.sliced=!a,c={hcJSON:{series:[]}},c.hcJSON.series[0]={data:[]},Ea(b.logic.chartInstance.jsVars._reflowData,
c,!0),a},placeDataLabels:function(){var a=function(a,b){return a.point.value-b.point.value},b=function(a,b){return a.angle-b.angle},c=["start","start","end","end"],f=[-1,1,1,-1],e=[1,1,-1,-1];return function(h,j){var k=this.datasets[0],s=this.smartLabel,o=this.options.plotOptions.series.dataLabels,m=o.style,v=g(parseInt(m.lineHeight,10),12),i=Da(o.placeInside,!1),A=o.skipOverlapLabels,u=o.manageLabelOverflow,B=o.connectorPadding,q=o.distance;Da(o.softConnector,!0);var Q=o.connectorWidth,p,y,q=q>0,
J=k.center,I=J[1],D=J[0],G=J[2],r=J[4],z=[[],[],[],[]],E,R,F,C=this.canvasLeft,H=this.canvasTop,N=this.canvasWidth,P,U,L,S,aa,W,oa,da,qa,Z,la,ea=k.labelsRadius,Y=k.labelsRadiusY,ha=k.labelFontSize,ca=ha,ja=ca/2,B=[B,B,-B,-B],ka=k.maxLabels,Ha=k.isSmartLineSlanted,na=k.enableSmartLabels,ma,k=k.pieSliceDepth/2;h||s.setStyle(m);if(j.length==1){if(S=j[0],ma=S.dataLabel,S.slicedTranslation=[C,H],ma)ma.attr({visibility:l,"text-anchor":"middle",x:D,y:I+ja-2}),ma.x=D}else if(i)ia(j,function(a){if(ma=a.dataLabel){la=
a.angle;Z=I+J[6]*ba(la)+ja-2;oa=D+J[5]*T(la);ma.x=oa;ma._x=oa;ma.y=Z;if(a.sliced){var a=a.slicedTranslation,b=a[1]-H;oa+=a[0]-C;Z+=b}ma.attr({visibility:l,align:"middle",x:oa,y:Z})}});else{ia(j,function(a){if(ma=a.dataLabel)la=a.angle,la<0&&(la=ga+la),E=la>=0&&la<fa?1:la<O?2:la<V?3:0,z[E].push({point:a,angle:la})});for(F=i=4;F--;){if(A&&(S=z[F].length-ka,S>0)){z[F].sort(a);R=z[F].splice(0,S);U=0;for(L=R.length;U<L;U+=1)S=R[U].point,S.dataLabel.attr({visibility:"hidden"}),S.connector&&S.connector.attr({visibility:"hidden"})}z[F].sort(b)}F=
M(z[0].length,z[1].length,z[2].length,z[3].length);Y=M(X(F,ka)*ca,Y);z[1].reverse();z[3].reverse();for(s.setStyle(m);i--;){U=z[i];L=U.length;A||(ca=L>ka?Y/L:ha,ja=ca/2);S=L*ca-ja;m=Y+ja;for(F=0;F<L;F+=1,S-=ca)y=Ga(Y*ba(U[F].angle)),m-y<ca?y=m-ca:y<S&&(y=S),m=U[F].oriY=y;R=c[i];L=Y-L*ca+ja;m=-ja;for(F=U.length-1;F>=0;F-=1,L+=ca){S=U[F].point;la=U[F].angle;aa=S.sliced;ma=S.dataLabel;y=Ga(Y*ba(la));y-m<ca?y=m+ca:y>L&&(y=L);m=y;da=(y+U[F].oriY)/2;y=D+e[i]*ea*T(n.asin(da/Y));da*=f[i];da+=I;qa=I+r*ba(la);
W=D+G*T(la);oa=y+B[i];Z=da+ja-2;p=oa+B[i];ma.x=p;ma._x=p;u&&(P=i>1?p-this.canvasLeft:this.canvasLeft+N-p,P=s.getSmartText(S.labelText,P,v),ma.attr({text:P.text,title:P.tooltext||""}));la<O&&(da+=k,qa+=k,Z+=k);ma.y=Z;if(aa)aa=S.transX,P=S.transY,oa+=aa,y+=aa,W+=aa,qa+=P,p+=aa;ma.attr({visibility:l,"text-anchor":R,x:p,y:da});if(q&&Q&&na)p=S.connector,S.connectorPath=y=[d,W,qa,t,Ha?y:W,da,oa,da],p?(p.attr({path:y}),p.attr("visibility",l)):S.connector=p=this.paper.path(y).attr({"stroke-width":Q,stroke:o.connectorColor||
"#606060",visibility:l})}}}}}(),legendClick:function(a,b,c){a=b.elements.plots[0];a.isRotating=!1;b.plotGraphicClick.call(a.items[c])}},k["renderer.root"]);k("renderer.pie",{drawPlotPie:function(a,b){var c=this,d=a.items,e=a.data,h=c.options,j=h.plotOptions,k=j.pie,n=j.series,o=c.layers,m=o.dataset,t=c.elements.plots[0],j=j.series.dataLabels,i=n.dataLabels.style,s=n.shadow,n=g(a.moveDuration,n.animation.duration),A=c.paper,h=(h=h.tooltip||{})&&h.enabled!==!1,B=(b.startAngle||0)%ga,q=k.slicedOffset,
u=ga/b.valueTotal,p=c.canvasLeft+c.canvasWidth*0.5,y=c.canvasTop+c.canvasHeight*0.5,J=k.size*0.5,I=(k.innerSize||0)*0.5,Q=c.plotGraphicClick,G=c.plotDragMove,r=c.plotDragStart,z=c.plotDragEnd,E=c.plotMouseDown,M=c.plotMouseUp,X=!!c.datasets[0].enableRotation,C,H,N,P,R,F,S,O,U,V,oa,da=a.shadowGroup,W,ca,Ga;if(!e||!e.length)e=[];if(!da)da=a.shadowGroup=A.group(m).toBack();t.singletonCase=e.length==1;t.chartPosition||(t.chartPosition=Aa(c.container));t.pieCenter=[p,y];t.timerThreshold=30;V=U=B;for(W=
e.length;W--;)if(H=e[W],N=H.y,P=H.displayValue,F=H.sliced,k=H.toolText,S=(R=!!H.link)||X||!H.doNotSlice,!(N===null||N===void 0)){C=H.color.FCcolor;C.r=J;C.cx=p;C.cy=y;V=U;U-=N*u;O=(U+V)*0.5;if(!(C=d[W]))if(b.data[W].plot=C=d[W]={chart:c,index:W,seriesData:t,value:N,angle:O,slicedX:T(O)*q,slicedY:ba(O)*q,sliced:F,labelText:P,graphic:A.ringpath(p,y,J,I,B,B,o.dataset).attr({"stroke-width":H.borderWidth,stroke:H.borderColor,fill:L(H.color),"stroke-dasharray":H.dashStyle,redrawDataLabels:B,ishot:S,cursor:R?
"pointer":""}).shadow(s&&H.shadow,da).drag(G,r,z).mousedown(E).mouseup(M)},H.doNotSlice||C.graphic.click(Q),h&&C.graphic.tooltip(k),b.data[W].legendClick=function(a){return function(){c.legendClick(null,c,a)}}(W),C.graphic.data("plotItem",C),P!==void 0&&(C.dataLabel=A.text(m).css(i).attr({text:P,fill:i.color||"#000000",ishot:S}).click(Q).drag(G,r,z).mousedown(E).mouseup(M).hide(),C.dataLabel.data("plotItem",C),j.distance>0&&(oa=j.connectorWidth)&&j.enableSmartLabels))C.connector=A.path("M 0 0 l 0 0",
m).attr({"stroke-width":oa,stroke:j.connectorColor||"#606060",visibility:l,ishot:!0}).click(Q).drag(G,r,z).mousedown(E).mouseup(M),C.connector.data("plotItem",C);C.angle=O;C.transX=T(O)*q;C.transY=ba(O)*q;C.slicedTranslation="t"+T(O)*q+","+ba(O)*q;ca?C.graphic.animateWith(ca,Ga,{ringpath:[p,y,J,I,U,V],transform:C.sliced?C.slicedTranslation:""},n,"easeIn"):(Ga=D.animation({ringpath:[p,y,J,I,U,V],redrawDataLabels:c,transform:C.sliced?C.slicedTranslation:""},n,"easeIn",function(){if(!c.disposed&&!c.disposing&&
!c.paper.ca.redrawDataLabels)c.placeDataLabels(!1,d,a),c.paper.ca.redrawDataLabels=c.redrawDataLabels}),ca=C.graphic.animate(Ga))}},rotate:function(a,b){var c=a.items,d=a.data,e=this.options.plotOptions.pie,h=e.slicedOffset,l=ga/b.valueTotal,g=this.canvasLeft+this.canvasWidth*0.5,k=this.canvasTop+this.canvasHeight*0.5,o=e.size*0.5,e=(e.innerSize||0)*0.5,m,n,i,t,s;t=(b.startAngle||0)%ga;for(s=d.length;s--;)if(n=d[s],m=n.y,!(m===null||m===void 0))n=t,t-=m*l,i=(t+n)*0.5,m=c[s],m.angle=i,m.transX=T(i)*
h,m.transY=ba(i)*h,m.slicedTranslation="t"+T(i)*h+","+ba(i)*h,m.graphic.attr({ringpath:[g,k,o,e,t,n],transform:m.sliced?m.slicedTranslation:""});this.placeDataLabels(!0,c,a)}},k["renderer.piebase"])},[3,2,2,"sr4"]]);
FusionCharts(["private","modules.renderer.js-zoomline",function(){var Aa=this,ha=Aa.hcLib,wa=window,wa=/msie/i.test(navigator.userAgent)&&!wa.opera,ya=ha.chartAPI,Ja=ha.chartAPI,na=ha.extend2,Ca=ha.raiseEvent,u=ha.pluck,D=ha.pluckNumber,Ba=ha.getFirstColor,F=ha.graphics.convertColor,Oa=ha.defaultPaletteOptions,q=ha.bindSelectionEvent,ta=ha.createTrendLine,g=ha.Raphael,Z=ha.FC_CONFIG_STRING,Da="rgba(192,192,192,"+(wa?0.0020:1.0E-6)+")",ua=Math,pa=ua.ceil,ea=ua.floor,Ea=ua.max,Ka=ua.min,L=ua.cos,Fa=
ua.sin,La=parseFloat,Y=parseInt,za=function(b){return b&&b.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")},ia;na(ha.eventList,{zoomed:"FC_Zoomed",pinned:"FC_Pinned",resetzoomchart:"FC_ResetZoomChart"});ya("zoomline",{rendererId:"zoomline",standaloneInit:!0,hasVDivLine:!0,defaultSeriesType:"stepzoom",canvasborderthickness:1,defaultPlotShadow:1,chart:function(){var b=this.base.chart.apply(this,arguments),e=this.dataObj.chart,l=Oa.canvasBorderColor[this.paletteIndex],d=b.chart;na(d,{animation:!1,zoomType:"x",
canvasPadding:D(e.canvaspadding,0),scrollColor:Ba(u(e.scrollcolor,Oa.altHGridColor[d.paletteIndex])),scrollBtnWidth:D(e.scrollbtnwidth,e.scrollheight,16),scrollHeight:D(e.scrollheight,16)||16,allowPinMode:D(e.allowpinmode,1),skipOverlapPoints:D(e.skipoverlappoints,1),showToolBarButtonTooltext:D(e.showtoolbarbuttontooltext,1),btnResetChartTooltext:u(e.btnresetcharttooltext,"Reset Chart"),btnZoomOutTooltext:u(e.btnzoomouttooltext,"Zoom out one level"),btnSwitchToZoomModeTooltext:u(e.btnswitchtozoommodetooltext,
"<strong>Switch to Zoom Mode</strong><br/>Select a subset of data to zoom into it for detailed view"),btnSwitchToPinModeTooltext:u(e.btnswitchtopinmodetooltext,"<strong>Switch to Pin Mode</strong><br/>Select a subset of data and compare with the rest of the view"),pinPaneFill:F(u(e.pinpanebgcolor,l),D(e.pinpanebgalpha,15)),zoomPaneFill:F(u(e.zoompanebgcolor,"#b9d5f1"),D(e.zoompanebgalpha,30)),zoomPaneStroke:F(u(e.zoompanebordercolor,"#3399ff"),D(e.zoompaneborderalpha,80))});return b},preSeriesAddition:function(){var b=
this.dataObj,e=b.chart,l=(l=b.categories)&&l[0]||{},d=l.category,b=this.hcJSON,g=b[Z],h=this.smartLabel,A=D(e.compactdatamode,0),n=u(e.dataseparator,"|"),q=D(e.showlabels,1),T=q&&D(e.labelheight),Q=e.labeldisplay&&e.labeldisplay.toLowerCase()==="rotate"?270:D(e.rotatelabels,1)?270:0,s=b.xAxis.labels.style,X=La(s.lineHeight),M=b.chart.labelPadding=D(e.labelpadding,2)+b.chart.plotBorderWidth,F,W;delete l.category;b.categories=F=na({data:n=A&&d&&d.split&&d.split(n)||d||[],rotate:Q},l);d!==void 0&&(l.category=
d);l=n.length||0;for(d=!A&&q&&T!==0&&l||0;d--;)n[d]=n[d]&&(W=n[d].label)||"";A&&l&&(W=n[0]);T===void 0&&q&&(W?(h.setStyle(s),W=h.getSmartText(W),T=Q?W.width:W.height):T=X*(Q&&3||1));T>g.height*0.5&&(T=g.height*0.5);F.labelHeight=T&&T+5||0;F.show=T&&q||0;F.css=na({},s);Q?(F.css.rotation=Q,F.css["text-anchor"]="end"):F.css["vertical-align"]="top";b.xAxis.min=0;b.xAxis.max=l&&l-1||0;T+=D(e.scrollheight,16)||16;b.chart.marginBottom+=M;g.marginBottomExtraSpace+=T;u(e.caption,e.subcaption)||(g.marginTopExtraSpace+=
16)},series:function(){var b=this.dataObj,e=b.chart,l=b.dataset,d=this.hcJSON,g=d[Z],h=g[0],A=d.series,n=D(e.yaxismaxvalue),q=D(e.yaxisminvalue),T=D(e.forceyaxislimits,0),Q=D(e.compactdatamode,0),s=u(e.dataseparator,"|"),X=za(e.indecimalseparator),M=za(e.inthousandseparator),F=D(e.drawanchors,e.showanchors,1),W=!!D(e.showlegend,1),L,R,qa,O,fa,ga=Infinity,V=-Infinity,da;fa=d.categories.data.length;if(l&&l.length&&fa){X&&(X=RegExp(X,"g"));M&&(M=RegExp(M,"g"));!M&&!X&&Q&&T&&n!==void 0&&q!==void 0?(T=
!0,V=Ea(n,q),ga=Ka(q,n)):T=!1;n=0;for(q=l.length;n<q;n++){L=l[n];qa=L.data;delete L.data;Q?(O=qa||"",M&&(O=O.replace(M,"")),X&&(O=O.replace(X,".")),O=O.split(s)):O=qa||[];if(O.length>fa)O.length=fa;da=O.length;if(Q){if(!T)for(;da--;)R=La(O[da]),isNaN(R)&&(R=void 0),R>V&&(V=R),R<=ga&&(ga=R),O[da]=R}else for(;da--;)R=O[da]&&O[da].value||"",M&&(R=R.replace(M,"")),X&&(R=R.replace(X,".")),R=La(R),isNaN(R)&&(R=void 0),R>V&&(V=R),R<=ga&&(ga=R),O[da]=R;A.push(R={index:n,type:"zoomline",data:O,name:L.seriesname||
"",showInLegend:L.seriesname&&D(L.includeinlegend,1)&&W||!1,showAnchors:D(L.drawanchors,L.showanchors,F),visible:!!D(L.initiallyvisible,1),lineWidth:2});O.length=fa;qa!==void 0&&(L.data=qa);R.attrs=this.seriesGraphicsAttrs(L,n);L=R.attrs.anchors;R.color=R.attrs.graphics.stroke;R.ancorRadius=L.r+L["stroke-width"]/2;R.marker={fillColor:L.fill,lineColor:L.stroke,lineWidth:1,symbol:"circle"}}(V===-Infinity||ga===Infinity)&&(V=ga=void 0);T=Y(D(e.displaystartindex,1),10)-1;s=Y(D(e.displayendindex,fa||2),
10)-1;(l=D(e.pixelsperpoint,15))<15&&(l=15);(A=D(e.pixelsperlabel,d.categories.rotate?20:60))<l&&(A=l);(T<0||T>=(fa-1||1))&&(T=0);(s<=T||s>(fa-1||1))&&(s=fa-1||1);d.stepZoom={cnd:D(e.connectnulldata,0),amrd:D(e.anchorminrenderdistance,20),nvl:D(e.numvisiblelabels,0),cdm:Q,oppp:l,oppl:A,dsi:T,dei:s,vdl:s-T,dmax:h.max=V,dmin:h.min=ga,clen:fa,offset:0,step:1,llen:0,alen:0,ddsi:T,ddei:s};d.crossline={style:{lineHeight:g.inCanvasStyle.lineHeight,fontSize:g.inCanvasStyle.fontSize,fontFamily:g.inCanvasStyle.fontFamily}};
this.configureAxis(d,b);b.trendlines&&ta(b.trendlines,d.yAxis,g,!1,this.isBar)}},seriesGraphicsAttrs:function(b,e){var l=this.dataObj.chart,d=this.hcJSON.colors,t=(b.dashed||l.linedashed||"0")!=0,h,d={"stroke-width":D(b.linethickness,l.linethickness,2),stroke:Ba(u(b.color,l.linecolor,d[e%d.length])),"stroke-opacity":D(b.alpha,l.linealpha,100)/100,"stroke-dasharray":t?[D(b.linedashlen,l.linedashlen,5),D(b.linedashgap,l.linedashgap,4)]:"none","stroke-linejoin":"round","stroke-linecap":"round"},t=na({},
d);h=d["stroke-width"]+D(l.pinlinethicknessdelta,1);t["stroke-width"]=h>0&&h||0;t["stroke-dasharray"]=[3,2];return{graphics:d,pin:t,shadow:{opacity:d["stroke-opacity"],apply:D(l.showshadow,+!g.vml)},anchors:{"stroke-linejoin":"round","stroke-linecap":"round",r:D(b.anchorradius,l.anchorradius,d["stroke-width"]+2),stroke:Ba(u(b.anchorbordercolor,l.anchorbordercolor,d.stroke)),"stroke-opacity":D(b.anchorborderalpha,l.anchorborderalpha,100)/100,"stroke-width":D(b.anchorborderthickness,l.anchorborderthickness,
d["stroke-width"]),fill:Ba(u(b.anchorbgcolor,l.anchorbgcolor,"#ffffff")),"fill-opacity":D(b.anchorbgalpha,l.anchorbgalpha,100)/100,opacity:D(b.anchoralpha,l.anchoralpha,100)/100}}},eiMethods:{zoomOut:function(){var b=this.jsVars,e;if(b&&(e=b.hcObj))return e.zoomOut&&b.hcObj.zoomOut()},zoomTo:function(b,e){var l=this.jsVars,d;if(l&&(d=l.hcObj))return d.zoomRange&&l.hcObj.zoomRange(b,e-2)},resetChart:function(){var b=this.jsVars,e;if(b&&(e=b.hcObj))e.pinRange&&b.hcObj.pinRange(),e.resetZoom&&b.hcObj.resetZoom()},
setZoomMode:function(b){var e=this.jsVars,l;e&&(l=e.hcObj)&&b&&l.pinRange&&e.hcObj.pinRange()},getViewStartIndex:function(){var b=this.jsVars,e;if(b&&b.hcObj&&(e=b.hcObj._zoominfo))return e.ddsi+1},getViewEndIndex:function(){var b=this.jsVars,e;if(b&&b.hcObj&&(e=b.hcObj._zoominfo))return b=e.ddei-1,b>e.clen?e.clen:b}}},ya.msline);Ja("renderer.zoomline",{resetZoom:function(){var b=this._zoomhistory,e=this.options.stepZoom;if(!b.length)return!1;b.length=0;this.zoomTo(e.dsi,e.dei)&&Ca("resetzoomchart",
this._zoomargs,this.fusionCharts,[this.fusionCharts.id]);return!0},zoomOut:function(){var b=this._zoomhistory.pop(),e=this.options.stepZoom,l,d,g;b?(l=b.dsi,d=b.dei):this._prezoomed&&(l=0,d=e.clen-1);(g=this.zoomTo(l,d))&&Aa.raiseEvent("zoomedout",g,this.fusionCharts);return!0},zoomRangePixels:function(b,e){var l=this._zoomhistory,d=this._zoominfo,g=d.ppp,d=d.ddsi,h;l.push(this._zoominfo);(h=this.zoomTo(d+ea(b/g),d+ea(e/g)))?Aa.raiseEvent("zoomedin",h,this.fusionCharts):l.pop()},zoomRange:function(b,
e){var l=this._zoomhistory,d;l.push(this._zoominfo);(d=this.zoomTo(+b-1,+e+1))?Aa.raiseEvent("zoomedin",d,this.fusionCharts):l.pop()},zoomTo:function(b,e){var l=this.xlabels.data,d=this._zoominfo,g=this._zoomhistory,h=d.clen;b<0&&(b=0);b>=h-1&&(b=h-1);e<=b&&(e=b+1);e>h-1&&(e=h-1);if(b===e||b===d.dsi&&e===d.dei)return!1;this.pinRange();d=na({},d);d.dsi=b;d.dei=e;d=this._zoominfo=d;this.updatePlotZoomline();this.zoomOutButton[d.vdl===d.clen-1?"hide":"show"]();this.resetButton[g.length?"show":"hide"]();
this.elements.zoomscroller.attr({"scroll-ratio":d.vdl/(h-!!h),"scroll-position":[d.dsi/(h-d.vdl-1),!0]});l={level:g.length+1,startIndex:b,startLabel:l[b],endIndex:e,endLabel:l[e]};Ca("zoomed",l,this.fusionCharts,[this.fusionCharts.id,b,e,l.startLabel,l.endLabel,l.level]);return l},activatePin:function(b){var e=this._zoominfo,l=this.options.chart,d=this.pinButton;if(d&&e.pinned^(b=!!b))return b||this.pinRange(),l.showToolBarButtonTooltext&&d.tooltip(l[b&&"btnSwitchToZoomModeTooltext"||"btnSwitchToPinModeTooltext"]||
""),d.attr("button-active",b),e.pinned=b},pinRange:function(b,e){var l=this.paper,d=this.elements,t=this.xlabels.data,h=this._zoominfo,A=this.layers.zoompin,n=d.pinrect,q=d["clip-pinrect"],u=this._pingrouptransform,Q=this.plots,s=e-b,F,M;if(h&&A&&n){if(b===e)return A.hide(),d.pintracker.hide(),this.pinButton.attr("button-active",!1),h.pinned=!1;for(M=Q.length;M--;){n=Q[M];F=n.pinline;if(!F)F=n.pinline=l.path(void 0,A).attr(n.attrPin);F.attr("path",n.graphic.attrs.path)}q[0]=b+(g.svg?this.canvasLeft:
0);q[2]=s;A.attr({"clip-rect":q,transform:u}).show();d.pintracker.__pindragdelta=0;d.pintracker.show().attr({transform:u,x:b,width:s});b=this.getValuePixel(b);e=this.getValuePixel(e);Ca("pinned",{startIndex:b,endIndex:e,startLabel:t[b],endLabel:t[e]},this.fusionCharts,[this.fusionCharts.id,b,e,t[b],t[e]]);return h.pinned=!0}},getValuePixel:function(b){var e=this._zoominfo;return e.ddsi+ea(b/e.ppp)},drawGraph:function(){var b=this,e=b.paper,l=b.canvasLeft,d=b.canvasTop,t=b.canvasWidth,h=b.canvasHeight,
A=b.options,n=A.chart,u=n.plotBorderWidth,F=n.showToolBarButtonTooltext,Q=b.layers,s=b.toolbar,D=b.elements,M=n.allowPinMode,L,W=A.categories,Z=!1,R,Y,O,fa,ga,V;V=b._zoominfo=na({},A.stepZoom);b._zoomhistory=[];if(V.clen){Z=b._prezoomed=V.dei-V.dsi<V.clen-1;ga=b._visw=b.canvasWidth-n.canvasPadding*2;fa=b._visx=b.canvasLeft+n.canvasPadding;b._visout=-(b.chartHeight+b.canvasHeight+1E3);b.base.drawGraph.apply(b,arguments);b._ypvr=b.yAxis[0]&&b.yAxis[0].pixelValueRatio||0;L=b._yzero||0;A=Q.dataset.attr("clip-rect",
[b._visx,b.canvasTop,b._visw,b.canvasHeight]);O=Q.scroll||(Q.scroll=e.group("scroll").insertAfter(Q.layerAboveDataset));b.xlabels=[];b.xlabels.show=W.show;b.xlabels.rotate=W.rotate;b.xlabels.data=W.data||[];b.xlabels.css=W.css;b.xlabels.group=e.group("zoomline-plot-xlabels",Q.datalabels);Q.datalabels.transform(["T",fa,d+h+n.scrollHeight+n.labelPadding]);b._lcmd=W.rotate?"y":"x";if(M)M=g.crispBound(0,d-L,0,h,u),R=D["clip-pinrect"]=[M.x,g.svg?d:M.y,M.width,M.height],Y=Q.zoompin=e.group("zoompin").insertBefore(A).transform(b._pingrouptransform=
["T",fa,L]).hide(),D.pinrect=e.rect(0,d-L,b._visw,h,Q.zoompin).attr({"stroke-width":0,stroke:"none",fill:n.pinPaneFill,"shape-rendering":"crisp",ishot:!0}),D.pintracker=e.rect(Q.tracker).attr({transform:Y.transform(),x:0,y:d-L,width:0,height:h,stroke:"none",fill:Da,ishot:!0,cursor:g.svg&&"ew-resize"||"e-resize"}).drag(function(b){var d=fa+b+this.__pindragdelta,e=this.__pinboundleft,h=this.__pinboundright;d<e?d=e:d>h&&(d=h);Y.transform(["T",d,L]);D.pintracker.transform(Y.transform());this.__pindragoffset=
b},function(){this.__pinboundleft=0-R[0]+fa+(g.svg&&l||0);this.__pinboundright=this.__pinboundleft+ga-R[2];Y._.clipispath=!0},function(){Y._.clipispath=!1;this.__pindragdelta=this.__pindragoffset;delete this.__pindragoffset;delete this.__pinboundleft;delete this.__pinboundright}),b.pinButton=s.add("pinModeIcon",function(){b.activatePin(!b._zoominfo.pinned)},{tooltip:F&&n.btnSwitchToPinModeTooltext||""});M=g.crispBound(l-u,d+h+u,t+u+u,n.scrollHeight,u);D.zoomscroller=e.scroller(M.x,M.y,M.width,M.height,
!0,{showButtons:!0,scrollRatio:V.vdl/(V.clen-!!V.clen),scrollPosition:[V.dsi/(V.clen-V.vdl-1),!1]},O).attr("fill",n.scrollColor).scroll(b.updatePlotZoomline,b);q(b,function(d){var e=d.selectionLeft-l,d=e+d.selectionWidth;b.crossline&&b.crossline.hide();b[b._zoominfo.pinned?"pinRange":"zoomRangePixels"](e,d)},{attr:{stroke:n.zoomPaneStroke,fill:n.zoomPaneFill,strokeWidth:0}});b.zoomOutButton=s.add("zoomOutIcon",function(){b.zoomOut()},{tooltip:F&&n.btnZoomOutTooltext||""})[Z&&"show"||"hide"]();b.resetButton=
s.add("resetIcon",function(){b.resetZoom()},{tooltip:F&&n.btnResetChartTooltext||""}).hide();M=b.resetButton.attr("fill");M[2]="rgba(255,255,255,0)";b.resetButton.attr("fill",[M[0],M[1],M[2],M[3]]);b.crossline=new ia(b);b.updatePlotZoomline()}},drawPlotZoomline:function(b,e){var l=this.paper,d=this._yzero||(this._yzero=this.yAxis[0].getAxisPosition(0)),g=e.attrs,h=e.visible,A=h?"show":"hide",n=this.layers.dataset,q=b.group||(b.group=l.group("plot-zoomline-dataset",n)),n=b.anchorGroup||(b.anchorGroup=
l.group("plot-zoomline-anchors",n)),l=b.graphic||(b.graphic=l.path(void 0,q)),d=["T",this._visx,d];q.transform(d)[A]();n.transform(d)[A]();b.graphic=l.attr(g.graphics).shadow(g.shadow);b.attrPin=g.pin;b.visible=h;b.anchors=[];b.anchors.show=e.showAnchors;b.anchors.attrs=g.anchors;b.anchors.left=-(g.anchors.r+g.anchors["stroke-width"]*0.5);b.anchors.right=this._visw-b.anchors.right},updatePlotZoomline:function(b,e){var g=this.paper,d=this._ypvr,t=this._visw,h=this.xlabels,q=h.css,n=h.group,u=this.plots,
F,Q,s,D,M,L;!e&&(e=this._zoominfo);Q=e.oppp;s=e.vdl=e.dei-e.dsi;e.ppl=e.oppl;D=e.ppl=e.nvl?t/e.nvl:e.oppl;t=e.step=(M=e.ppp=t/s)<Q?pa(Q/M):1;Q=e.lskip=pa(D/M/t);b!==void 0?(D=(e.clen-s-1)*b,e.offset=(D-(D=Y(D)))*M,L=D+s):(D=e.dsi,L=e.dei,e.offset=0);s=e.norm=D%t;e.ddsi=D-=s;e.ddei=L=L+2*t-s;e.pvr=d;d=h.show?pa((L-D)/t/Q):0;Q=e.llen-1;e.llen=d;if(d>Q){s=Q;for(Q=d;s<Q;s++)(F=h[s])&&F.show()||(h[s]=g.text(0,0,"",n).css(q))}else{s=d;for(Q+=1;s<Q;s++)h[s].hide()}d=M*t<e.amrd?0:pa((L-D)/t);M=d-e.alen;e.alen=
d;for(t=u.length;t--;){q=u[t];n=q.anchors;if(n.show&&M){F=n.attrs;s=0;for(Q=d;s<Q;s++)n[s]=n[s]&&n[s].show()||g.circle(0,0,0,q.anchorGroup).attr(F);s=d;for(Q=n.length;s<Q;s++)n[s]&&n[s].hide()}this.drawPlotZoomlineGraphics(e,q.data,q.graphic,n,!t&&h)}if(window.FC_DEV_ENVIRONMENT)FusionCharts.debugMode.enabled()?(this.debug=this.debug||($("#fc-zoominfo").length||$("body").append('<pre id="fc-zoominfo">'),$("#fc-zoominfo").css({position:"absolute",left:"10px",top:"0","pointer-events":"none",opacity:0.7,
width:"250px",zIndex:"999",border:"1px solid #cccccc","box-shadow":"1px 1px 3px #cccccc",background:"#ffffff"})),this.debug.text(JSON.stringify(e,0,2))):($("#fc-zoominfo").remove(),delete this.debug)},drawPlotZoomlineGraphics:function(b,e,g,d,t){var h=[],q=!b.cnd,n=b.ddei,u=b.clen,D=b.step,F=b.lskip,s=b.ppp,L=b.offset,M=b.pvr,Y=this._visw,W=this._visout,Z=this._lcmd,R="M",ea,O,fa=t&&t[0],ga=fa&&t.data,d=d[0],V={},da={},U,ja=0,ha,ia=-b.norm,b=b.ddsi,ca=0;for(fa&&t.group.transform(["T",-L,0]);b<=n;b+=
D,ia+=D)if(ha=ja/3+ca,U=ia*s,(ea=e[b])===void 0?(q&&(R="M"),O=W,t=U-L,ea=W,ca++):(h[ja++]=R,h[ja++]=O=t=U-L,h[ja++]=ea*=M,R="L"),d&&(d=d.attr((V.cx=O,V.cy=ea,V)).next),fa&&!(ha%F))ha=fa.attrs,O=ga[b]||"",t=t<0||t>Y?W:U,ha.text===O?delete da.text:da.text=O,ha[Z]===t?delete da[Z]:da[Z]=t,fa=fa.attr(da).next;if(n>=u){if((ea=e[u-1])!==void 0)ia-=n-u,h[ja++]="L",h[ja++]=ia*s-L,h[ja++]=ea*M;d&&d.attr((V.cx=W,V.cy=W,V))}g.attr("path",h)},legendClick:function(b){var e=!b.visible,g=e?"show":"hide";b.group[g]();
b.anchorGroup[g]();this.base.legendClick.apply(this,arguments);return b.visible=e}},Ja["renderer.cartesian"]);ia=function(b){var e=b.paper,g=this.left=b._visx,d=this.width=b._visw,t=b.canvasTop,h=b.canvasHeight,q=b._visout,n=this.plots=b.plots,u=b.layers.dataset,D=this.group=e.group("crossline-labels",u).attr({transform:["T",g,b._yzero]});this.tracker=e.rect(g,t,d,h,u).attr({stroke:"none","stroke-width":0,fill:Da}).toFront().mousedown(this.onMouseDown,this).mouseup(this.onMouseUp,this,!0).mouseout(this.onMouseOut,
this).mousemove(this.onMouseMove,this);this.line=e.path(void 0,u).attr({path:["M",g,t,"l",0,h],"stroke-opacity":0.2}).toBack();g=this.labels=e.set();d=b.options.crossline.style;this.hide();this.pixelRatio=b._ypvr;this.getZoomInfo=function(){return b._zoominfo};this.getDataIndexFromPixel=function(d){return b.getValuePixel(d)};t=0;for(h=n.length;t<h;t++)u=n[t],u=u.graphic.attrs.stroke,g.push(e.text(0,q,"",D).css(d).attr({fill:u,"text-bound":["rgba(255,255,255,0.8)","rgba(0,0,0,0.2)",1,2]}))};ia.prototype.onMouseOut=
function(){this.hide()};ia.prototype.onMouseDown=function(){this.hide();this._mouseIsDown=!0};ia.prototype.onMouseUp=function(){this.hide();delete this._mouseIsDown};ia.prototype.onMouseMove=function(b){if(!this._mouseIsDown){var e=this.getZoomInfo(),g=this.line,d=e.step,t=e.ppp*d,b=(b.layerX||b.x)-this.left,h,b=(b+=t/2+e.offset)-b%t;h=(h=this.getDataIndexFromPixel(b))+h%d;b-=e.offset;g.transform(["T",ea(b),0]);if(h!==this.position||this.hidden)this.position=h,this.lineX=b,this.updateLabels();this.hidden&&
this.show()}};ia.prototype.updateLabels=function(){var b=this.plots,e=this.width,g=this.position,d=this.lineX,t=this.pixelRatio,h;this.labels.forEach(function(q,n){h=b[n].data[g];q.attr({text:h+"",x:ea(d),y:h===void 0?-1E3:h*t,"text-anchor":d<=0&&"start"||d>=e&&"end"||"middle"})})};ia.prototype.show=function(){this.hidden=!1;this.group.show();this.line.show()};ia.prototype.hide=function(){this.hidden=!0;this.group.hide();this.line.hide()};g.addSymbol({pinModeIcon:function(b,e,g){var d=g*0.5,t=b-g,
h=b+g,q=b-d,n=b+d,u=b+0.5,D=u+1,F=u+1.5,s=e-g,L=e+d,M=e-d,d=e+(g-d);return["M",t,s,"L",q,M,q,d,t,L,b-0.5,L,b,e+g+0.5,u,L,h,L,n,d,n,M,h,s,F,s,F,M,F,d,D,d,D,M,F,M,F,s,"Z"]},zoomOutIcon:function(b,e,l){b-=l*0.2;e-=l*0.2;var d=l*0.8,t=g.rad(43),h=g.rad(48),q=b+d*L(t),t=e+d*Fa(t),n=b+d*L(h),h=e+d*Fa(h),u=g.rad(45),D=q+l*L(u),F=t+l*Fa(u),s=n+l*L(u),l=h+l*Fa(u);return["M",q,t,"A",d,d,0,1,0,n,h,"Z","M",q+1,t+1,"L",D,F,s,l,n+1,h+1,"Z","M",b-2,e,"L",b+2,e,"Z"]},resetIcon:function(b,e,g){var d=b-g,q=(ua.PI/
2+ua.PI)/2;b+=g*L(q);var q=e+g*Fa(q),h=g*2/3;return["M",d,e,"A",g,g,0,1,1,b,q,"L",b+h,q-1,b+2,q+h-0.5,b,q]}})}]);